<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profiletab</name>
   <tag></tag>
   <elementGuidId>1a8c0fcd-e890-4764-8e06-4e2e0e52a861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profile-tab']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile-tab > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2172fa6d-0067-402e-b445-34eb83f0aa85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROFILE</value>
      <webElementGuid>f335c331-376b-4071-b171-3b449199e75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile-tab&quot;)/span[1]</value>
      <webElementGuid>28f4ca9f-54dd-4612-b0a4-f370eb94318a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='profile-tab']/span</value>
      <webElementGuid>2ca257af-664c-4055-a75c-e966b231ff91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER SETTINGS'])[1]/following::span[1]</value>
      <webElementGuid>fbbe13d4-dd5f-46b2-8a3b-84d1122cb2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[2]/following::span[2]</value>
      <webElementGuid>3f34772f-7bb0-4abf-813c-d558ab1dec2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESS'])[1]/preceding::span[1]</value>
      <webElementGuid>93dbc6f0-7d5a-4742-b524-a276e5b388a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT ACCEPTANCE'])[1]/preceding::span[2]</value>
      <webElementGuid>323fd9f4-c013-47c4-8e54-3fcea1bef960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span</value>
      <webElementGuid>71c1b45a-5c8b-4b79-a9a3-70362f3eb0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PROFILE' or . = 'PROFILE')]</value>
      <webElementGuid>cc133ef9-fe82-4bc6-9809-a9d150f37142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
