<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toaster_container</name>
   <tag></tag>
   <elementGuidId>591a0477-bb80-4851-97d8-adb5f72d5a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[16]/div[count(. | //div[@class = 'toast toast-error']) = count(//div[@class = 'toast toast-error'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4620c34-166b-43bc-8d83-3ca9434c1cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast toast-error</value>
      <webElementGuid>70d78f78-c8ce-4f89-b3da-6b00aa085cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[16]/div</value>
      <webElementGuid>08eb7827-6934-4e94-851f-4539880ab9c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
