<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address toaster</name>
   <tag></tag>
   <elementGuidId>44fa6be1-7cb7-44f9-ab73-6654842c5824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.toast.toast-error</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'toast toast-error' and (text() = 'Oops! Something went wrong.An address is required to continue' or . = 'Oops! Something went wrong.An address is required to continue')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cacf0ff-3dc0-41f9-a784-7f8a3421e34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast toast-error</value>
      <webElementGuid>e8c33f06-3ecd-4263-b3fe-552c0b662749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oops! Something went wrong.An address is required to continue</value>
      <webElementGuid>d4e63623-e608-43fb-8296-1ab62a90f899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[16]/div</value>
      <webElementGuid>1f700f24-3019-4ccf-bf65-2efc0233cab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>9ebd81f6-5674-4e4d-a4dd-73970c759e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-container', '&quot;', ')/div[@class=', '&quot;', 'toast toast-error', '&quot;', ']')])[1]/following::div[2]</value>
      <webElementGuid>fa15d747-9f8f-4346-958b-ec2886195227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>9ce4bb48-42a4-4516-bc6d-28f0972caf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div</value>
      <webElementGuid>a3b89eb7-3bb8-4535-8777-8599081a97cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Oops! Something went wrong.An address is required to continue' or . = 'Oops! Something went wrong.An address is required to continue')]</value>
      <webElementGuid>456a1400-23f4-4f8a-b1d1-7cb59d782df9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
