<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Oops Something went wrong.Please add a profile image</name>
   <tag></tag>
   <elementGuidId>f2d4ec3d-bf0e-46ec-b270-c59b3974529a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.toast.toast-error</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[17]/div[count(. | //div[@class = 'toast toast-error' and (text() = 'Oops! Something went wrong.Please add a profile image' or . = 'Oops! Something went wrong.Please add a profile image')]) = count(//div[@class = 'toast toast-error' and (text() = 'Oops! Something went wrong.Please add a profile image' or . = 'Oops! Something went wrong.Please add a profile image')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18a2b9a8-7cf3-4759-b35e-e88086b25dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast toast-error</value>
      <webElementGuid>0cdae2b7-cfd7-4f50-b4b9-f6ee85f3982b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oops! Something went wrong.Please add a profile image</value>
      <webElementGuid>a903d921-3b87-4365-8f98-4b11855038a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[17]/div</value>
      <webElementGuid>61154547-41f5-4d28-b05e-c063ec41be0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>bd678a2a-eae4-45d6-810c-565f173694fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-container', '&quot;', ')/div[@class=', '&quot;', 'toast toast-error', '&quot;', ']')])[1]/following::div[2]</value>
      <webElementGuid>30d2f771-7da4-4edd-8d5f-fcdc70c13778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>f250af4d-2e41-4122-9878-5f2a254ff8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div</value>
      <webElementGuid>a40a432e-cd9d-43f0-8bf2-61e6666d643b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Oops! Something went wrong.Please add a profile image' or . = 'Oops! Something went wrong.Please add a profile image')]</value>
      <webElementGuid>b6dfb3d3-4b8c-401c-b665-78b3d118a7f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
