<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_text_2</name>
   <tag></tag>
   <elementGuidId>cfaa3b7b-df49-43bb-821b-feb51a06943b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[16]/div/div/div[1]/div[count(. | //div[@class = 'bootbox-body' and (text() = 'Are you sure want to delete?' or . = 'Are you sure want to delete?')]) = count(//div[@class = 'bootbox-body' and (text() = 'Are you sure want to delete?' or . = 'Are you sure want to delete?')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c73db9f-f754-4d32-88e2-2820b43f2299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bootbox-body</value>
      <webElementGuid>ca3e282d-c838-4ab5-be28-c62ef24ba618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are you sure want to delete?</value>
      <webElementGuid>db0ec9b9-ae45-414c-828c-86d3ff0fbad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[16]/div/div/div[1]/div</value>
      <webElementGuid>4daeaf3e-9bf5-438a-b3fa-39680c38dd77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
