<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>be_a_seller</name>
   <tag></tag>
   <elementGuidId>2c7fa45d-60b2-43f0-8caa-9d5f97550c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-modal-seller</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='register-modal-seller']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c90ab0b8-02d8-46fd-b2c3-51559f055d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>108041e9-2182-47c0-837c-73db56ec574b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-xs register-modal</value>
      <webElementGuid>2c8644f9-6f76-4d8e-8f79-4fdedbeb6e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-modal-seller</value>
      <webElementGuid>d831ec77-a8f5-4aa1-83ff-9695ed2c255c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BE A SELLER</value>
      <webElementGuid>63fbaf0e-cef9-4403-add6-69287cf247af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-modal-seller&quot;)</value>
      <webElementGuid>aa17ee1a-19c1-4f07-bf81-9d1ecdff1ef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='register-modal-seller']</value>
      <webElementGuid>9e5566c1-b948-4c1d-95d1-2439f3cb7b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='videoBannerBG']/div/div/div[2]/div/ul/li/a</value>
      <webElementGuid>ccda63d0-c467-471e-b71b-7189569bfca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BE A SELLER')]</value>
      <webElementGuid>1bf9ccdb-8705-4900-bdac-85f9d1e19838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW CART'])[1]/preceding::a[4]</value>
      <webElementGuid>8198b006-4e0b-4de8-a206-7d3431e3bf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THIS ITEM HAS BEEN ADDED!'])[1]/preceding::a[5]</value>
      <webElementGuid>c107b255-65c4-421c-8893-2d954cdf0b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BE A SELLER']/parent::*</value>
      <webElementGuid>9ef653d3-40a6-47b4-a03a-d7f81a65cae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>6c409e4b-632b-4bea-9a87-0ee3bbf9f8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>672a8c93-1eb5-4a27-ac1f-da2a5887ac0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'register-modal-seller' and (text() = 'BE A SELLER' or . = 'BE A SELLER')]</value>
      <webElementGuid>e4bcd33b-ce23-40b3-a676-f684e1360090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
