<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>create_btn_2</name>
   <tag></tag>
   <elementGuidId>c0f66133-b954-4a1d-aa20-b7c48c02f354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b64ecc4c-2cee-46ec-a5f0-fa38608d946b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fff445ae-a4e1-4a74-b0c0-f599b84c014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return signup_form_validate(event); </value>
      <webElementGuid>f6edd190-902c-4351-b8ea-5a16c1017e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account-submit</value>
      <webElementGuid>02d0c287-8f9f-45aa-97ca-1cc436744c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-submit</value>
      <webElementGuid>65014cdd-566f-406d-ab31-9ab246e80ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-btn</value>
      <webElementGuid>1a1b16a6-22ab-4762-990c-e5e44798c0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create Account</value>
      <webElementGuid>f08508e2-f8d3-47ba-a11c-a96e6ab1a81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-submit&quot;)</value>
      <webElementGuid>1460a114-31e2-48fe-ac44-501e4d38195e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account-submit']</value>
      <webElementGuid>be2b9f7f-3bb5-42c9-9728-f48ec4b85be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmaccount']/div[5]/input</value>
      <webElementGuid>c163024b-0d2f-4f72-a8d8-ee950669a399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>81766071-4441-40e0-9e88-1a037d94388f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'account-submit' and @id = 'account-submit']</value>
      <webElementGuid>6396b94e-c234-4e1c-8e2d-ac7d1ed91469</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
