<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>create_btn_1</name>
   <tag></tag>
   <elementGuidId>92e8fd2a-6fd7-4293-aff7-cd3158247038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create-account</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='create-account']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c8b9807-6a7e-44b0-9b7e-9e5f15609839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>332ed9d2-2652-4f45-9d5d-f66bd23d4c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create-account</value>
      <webElementGuid>5f549211-cbdd-44c0-b4e6-a90e3fdcc005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-account</value>
      <webElementGuid>468d2b51-50d3-4833-be1f-16db534ebd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-btn</value>
      <webElementGuid>16bad5bd-d283-4000-9f2e-933efafffa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create Account</value>
      <webElementGuid>fbd4abab-4050-457b-8445-52c8db38f174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-account&quot;)</value>
      <webElementGuid>af7eefa2-6f52-430f-98a8-2c2fa60e63ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='create-account']</value>
      <webElementGuid>0763999e-2706-41ee-aac1-3d3e4ecdd928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmlogin']/div[3]/input</value>
      <webElementGuid>4c557c06-0102-472b-84da-67bc201e7778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>69376dc8-9f81-4dc4-921a-acaf044ebfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'create-account' and @id = 'create-account']</value>
      <webElementGuid>be9ff2e9-0577-4b88-b486-0a97c1cebdb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
