<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>create_btn_1</name>
   <tag></tag>
   <elementGuidId>92e8fd2a-6fd7-4293-aff7-cd3158247038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='create-account']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create-account</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[1]/div[2]/form/div[3]/input[1][count(. | //input[@type = 'button' and @name = 'create-account' and @id = 'create-account']) = count(//input[@type = 'button' and @name = 'create-account' and @id = 'create-account'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17293840-5589-4b34-8d5b-f78aec2d292e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff2fd57d-2632-4e55-8115-5276713ec09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create-account</value>
      <webElementGuid>6ebaf28d-4752-4b01-8768-ab2c9802f27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-account</value>
      <webElementGuid>a4698682-a23c-4892-9b9a-58394d3cda6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-btn</value>
      <webElementGuid>88deca53-b9cb-40a8-8048-81f7ff20342b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create Account</value>
      <webElementGuid>5e1ecf34-65be-4ba9-bfc3-1abb0a03e16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[1]/div[2]/form/div[3]/input[1]</value>
      <webElementGuid>e31f5d30-8edd-4c89-ae49-9fae399ec9d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='create-account']</value>
      <webElementGuid>1400a638-6be8-4f37-85b0-28a2987b18b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmlogin']/div[3]/input</value>
      <webElementGuid>5c223590-7839-4a48-9b55-1f5e730d313d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>150c3d4d-a157-4050-a6d5-85d954a444d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'create-account' and @id = 'create-account']</value>
      <webElementGuid>1a6bca53-f7cd-4cc4-bf4f-f7839370dbc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
