<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>create_btn_2</name>
   <tag></tag>
   <elementGuidId>c0f66133-b954-4a1d-aa20-b7c48c02f354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#account-submit</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[5]/input[count(. | //input[@type = 'submit' and @name = 'account-submit' and @id = 'account-submit']) = count(//input[@type = 'submit' and @name = 'account-submit' and @id = 'account-submit'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc6e4f32-78ed-4c63-be86-7c5557694764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>687f071a-e158-4b1f-9901-f7b0402bb0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return signup_form_validate(event); </value>
      <webElementGuid>362f4982-283d-4258-ab26-7ea670b7ad90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account-submit</value>
      <webElementGuid>d293676b-bee7-478c-a5cc-b46a3315ab34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-submit</value>
      <webElementGuid>3477c9d2-0049-4ab1-a220-631fdbac61bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-btn</value>
      <webElementGuid>77cfd558-e275-4a0c-a7fa-0809bc57fb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create Account</value>
      <webElementGuid>db47c545-1fad-4422-9dcc-f43f9da3ccf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[5]/input</value>
      <webElementGuid>42da0bcd-994f-4fe9-89de-c3a246451d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account-submit']</value>
      <webElementGuid>3bd7f3af-b711-4066-8acb-a3eef192a98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmaccount']/div[5]/input</value>
      <webElementGuid>7dbbac3f-4446-4f79-a136-a8aacac6058f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>3118bbd7-b7c0-425a-b9a4-42541dd1dde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'account-submit' and @id = 'account-submit']</value>
      <webElementGuid>4a1d7ba5-d3c6-488f-9dcd-60252fdeda69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
