<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>invalid_email_txtlabel</name>
   <tag></tag>
   <elementGuidId>04450437-7163-403e-9236-a5eb8a336cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/div/span[count(. | //span[@class = 'email-error-sec' and (text() = 'Please enter valid email address' or . = 'Please enter valid email address')]) = count(//span[@class = 'email-error-sec' and (text() = 'Please enter valid email address' or . = 'Please enter valid email address')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f5638439-87f8-4ddd-8bbe-96f9082c420e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-error-sec</value>
      <webElementGuid>4947a14e-0dee-4d7b-a85b-a8b6448fc736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid email address</value>
      <webElementGuid>cc20025d-76e7-4e4f-9828-920af33d3e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/div/span</value>
      <webElementGuid>6e0b73b0-c8c6-436a-9f72-085af4b4b4f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
