<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>invalid_email_txtlabel</name>
   <tag></tag>
   <elementGuidId>04450437-7163-403e-9236-a5eb8a336cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/div/span[count(. | //span[@class = 'email-error-sec' and (text() = 'Please enter valid email address' or . = 'Please enter valid email address')]) = count(//span[@class = 'email-error-sec' and (text() = 'Please enter valid email address' or . = 'Please enter valid email address')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e980cb0-a958-44ea-82f0-e8e8949b39ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-error-sec</value>
      <webElementGuid>2a54e98e-69c4-4b77-949c-63690bba33c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid email address</value>
      <webElementGuid>f0ee3461-fea2-4624-8896-9f4b1bd92057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/div/span</value>
      <webElementGuid>90fa4aa0-abb1-4492-a925-1aa4e8c6ce31</webElementGuid>
   </webElementProperties>
</WebElementEntity>
