<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notif_email_txtlabel</name>
   <tag></tag>
   <elementGuidId>4aed665a-d90f-48dd-8cc8-ad2609ff6411</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmaccount']/div[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/label[count(. | //label[(text() = 'Notification email' or . = 'Notification email')]) = count(//label[(text() = 'Notification email' or . = 'Notification email')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>96085c6d-87c3-4edc-8943-b085a90db70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notification email</value>
      <webElementGuid>ab2f72ba-0305-4280-b4e7-2ac6003e67c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/label</value>
      <webElementGuid>4a74d68d-7a7b-4f84-be48-3a5566414b1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmaccount']/div[4]/label</value>
      <webElementGuid>42bf03fb-f33a-4d6c-bf23-a347d814b570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reconfirm password'])[1]/following::label[1]</value>
      <webElementGuid>ae27948a-8b99-4403-8f8c-0bdc66994207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your password'])[2]/following::label[2]</value>
      <webElementGuid>4c5bf2a1-8e7c-4588-acb1-959debccba8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already have an account?'])[1]/preceding::label[1]</value>
      <webElementGuid>35c81649-7464-4024-93b6-9da26059c270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[1]</value>
      <webElementGuid>8a11498b-17d6-48a6-a4ad-123c581c8038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notification email']/parent::*</value>
      <webElementGuid>0a0c723a-7784-4689-81e5-cb1a48e4f875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>e6748164-2a9a-4db6-9e99-87205fe015e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Notification email' or . = 'Notification email')]</value>
      <webElementGuid>52774856-7773-4723-abf9-7daec6975601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
