<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notif_email_txtbox</name>
   <tag></tag>
   <elementGuidId>c392676c-32a7-4a71-b1de-cb0072877c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nemail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nemail']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/input[count(. | //input[@type = 'text' and @class = 'singfrm-txtbox emailOnly']) = count(//input[@type = 'text' and @class = 'singfrm-txtbox emailOnly'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42ce62ec-5dc1-4080-9f2e-fdd6d01e9cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87fd5ac9-d015-446a-98de-9f40f67c4c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notificationemail</value>
      <webElementGuid>f3c7b828-0321-44b2-a397-53da1bd36e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nemail</value>
      <webElementGuid>b92a92fc-cc5b-47d2-b456-fd705697c4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>singfrm-txtbox emailOnly</value>
      <webElementGuid>7bb39441-8feb-42ca-95cb-818bed90bd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/input</value>
      <webElementGuid>cfae5e29-6c2f-4527-b3f7-664dea8caeb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nemail']</value>
      <webElementGuid>a6a4b80f-33b5-469f-abc7-8b48932ffe73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmaccount']/div[4]/input</value>
      <webElementGuid>d3dfb084-c33b-4eac-9ce2-31cebaaa1d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/input</value>
      <webElementGuid>fdb8c1be-5505-4b54-820c-3c7359fc1b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'notificationemail' and @id = 'nemail']</value>
      <webElementGuid>7bec7063-d983-4c17-a164-6d64e49780ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
