<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notif_email_txtbox</name>
   <tag></tag>
   <elementGuidId>c392676c-32a7-4a71-b1de-cb0072877c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nemail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nemail</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/input[count(. | //input[@type = 'text' and @name = 'notificationemail' and @id = 'nemail' and @class = 'singfrm-txtbox emailOnly']) = count(//input[@type = 'text' and @name = 'notificationemail' and @id = 'nemail' and @class = 'singfrm-txtbox emailOnly'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4c1a5e5-272d-406b-9aec-af34eb922239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93e1898d-f253-48dd-bedb-6018864cebc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notificationemail</value>
      <webElementGuid>20b8db93-6b4d-47f9-9b20-8442dab6920f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nemail</value>
      <webElementGuid>2bf5fb11-80bf-4d4a-9158-6c1f10f5d054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>singfrm-txtbox emailOnly</value>
      <webElementGuid>ba8ce58d-ab55-4eda-9321-126b8160699f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[4]/input</value>
      <webElementGuid>b4939743-a2a4-4999-a613-119ce753dcfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nemail']</value>
      <webElementGuid>811ed936-06c4-4445-817c-a20979383f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmaccount']/div[4]/input</value>
      <webElementGuid>14f19451-6bea-4a7c-a69b-d92085a6d1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/input</value>
      <webElementGuid>08d5cdc6-628d-4e6b-a5c5-0524b5f07a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'notificationemail' and @id = 'nemail']</value>
      <webElementGuid>c90d3c25-56ad-47bb-8816-53631bae6a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
