<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>reconfirm_pas_txtbox</name>
   <tag></tag>
   <elementGuidId>96634c78-9f72-4863-af20-3680a09bbe77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='reconfirm-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;reconfirm-password&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[3]/input[count(. | //input[@type = 'password' and @name = 'reconfirm-password']) = count(//input[@type = 'password' and @name = 'reconfirm-password'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>543958e6-3a1f-4408-b57a-925c2ee9121b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>720aa2ad-d09e-4675-99ea-154a94e004db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reconfirm-password</value>
      <webElementGuid>a00116a1-3102-4800-9137-a4b1ab3317cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>singfrm-txtbox required</value>
      <webElementGuid>984fb759-ab84-4fcf-8a1f-47250b05e671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[3]/input</value>
      <webElementGuid>2d5c34c9-72db-490c-b8f9-e8ceadc9a618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='reconfirm-password']</value>
      <webElementGuid>0569ebad-a8e3-49ab-8ecf-10dbc4e552c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmaccount']/div[3]/input</value>
      <webElementGuid>a7571bf6-42b5-432a-a187-3c0dc74a4258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[3]/input</value>
      <webElementGuid>719cd8cb-7409-479d-b164-795fa552770f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'reconfirm-password']</value>
      <webElementGuid>c5ed6911-b23c-4829-9f18-2633050588e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
