<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>reconfirm_pas_txtbox</name>
   <tag></tag>
   <elementGuidId>96634c78-9f72-4863-af20-3680a09bbe77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;reconfirm-password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='reconfirm-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5411b875-118d-42f3-a789-954d883fd1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b9fdb6ea-2290-4375-b73a-2af7aa95dc45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reconfirm-password</value>
      <webElementGuid>41cf039b-73fc-4a82-9a9c-9f6f012db338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>singfrm-txtbox required</value>
      <webElementGuid>8fb25df2-d02f-44df-85c0-3aa424dbd7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmaccount&quot;)/div[@class=&quot;signin-form-group&quot;]/input[@class=&quot;singfrm-txtbox required&quot;]</value>
      <webElementGuid>5fbe343b-be4d-416a-a4f7-d2dce4e35a19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='reconfirm-password']</value>
      <webElementGuid>0483ee53-3194-483e-97ef-44c986e414dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmaccount']/div[3]/input</value>
      <webElementGuid>ed58dc0c-9a1d-4235-82a3-2dde0c6f25cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[3]/input</value>
      <webElementGuid>be8733a4-ee89-4ff6-9544-fe1300c4a40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'reconfirm-password']</value>
      <webElementGuid>865f38c8-d61e-45e1-a012-3ff192879a40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
