<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>reconfirm_pas_txtbox</name>
   <tag></tag>
   <elementGuidId>96634c78-9f72-4863-af20-3680a09bbe77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='reconfirm-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;reconfirm-password&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[3]/input[count(. | //input[@type = 'password' and @name = 'reconfirm-password']) = count(//input[@type = 'password' and @name = 'reconfirm-password'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1475b4d1-e422-4d07-83fb-e1cc19405389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>55255ad5-96f5-4fdb-8b5e-8a38bed5c72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reconfirm-password</value>
      <webElementGuid>cb5172fd-3775-4ad4-9eb9-627a435047dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>singfrm-txtbox required</value>
      <webElementGuid>febaf2f4-5803-4f95-ac0c-eb539ba10111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div[1]/div[2]/form/div[3]/input</value>
      <webElementGuid>c7d79119-e69e-49f2-95c5-bcdc09f16ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='reconfirm-password']</value>
      <webElementGuid>3ea02ca3-4f44-4b9b-8aee-07532467f341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmaccount']/div[3]/input</value>
      <webElementGuid>0aeaf08d-7f01-4b0a-a530-383d7077ed90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[3]/input</value>
      <webElementGuid>50c4bd93-1049-4a66-8925-d9be1b900ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'reconfirm-password']</value>
      <webElementGuid>cd01829a-37d9-4a54-bd09-16f0edf4fa59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
