<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_NOTIFICATION EMAIL</name>
   <tag></tag>
   <elementGuidId>0a1f4fdd-10c0-4e6e-b4e4-f71d51fcf717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profile']/div/div/form/div[5]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>790c80c2-9d63-43e2-be64-156d2c8567fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NOTIFICATION EMAIL</value>
      <webElementGuid>1a9bc6ea-b119-4bbb-9457-6a4f08e13f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;seller-common-box&quot;]/form[1]/div[@class=&quot;item-form-group&quot;]/div[@class=&quot;col-md-6&quot;]/label[1]</value>
      <webElementGuid>bd0aecc8-afc1-41ea-84fd-69e36b16e0ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[5]/div/label</value>
      <webElementGuid>ba2a7e6b-355a-46c2-8c53-b212ba0faffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAST NAME'])[1]/following::label[1]</value>
      <webElementGuid>0e4890e2-b016-4463-b230-0160ade8efe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FIRST NAME'])[1]/following::label[2]</value>
      <webElementGuid>57b3890b-59a2-445f-9ed9-3ee6ec695321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT NUMBER'])[1]/preceding::label[1]</value>
      <webElementGuid>453c6e4a-8203-42fb-a91b-4763c32676c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPENID LOGIN'])[1]/preceding::label[2]</value>
      <webElementGuid>addd089c-3a70-40f6-b4c0-ae019f6c8fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NOTIFICATION EMAIL']/parent::*</value>
      <webElementGuid>507b13f5-e606-4f25-baa5-6599a5136ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label</value>
      <webElementGuid>339d47c8-8278-4a06-b67f-7b8c09b8aa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'NOTIFICATION EMAIL' or . = 'NOTIFICATION EMAIL')]</value>
      <webElementGuid>d62402fa-828b-4eb3-9015-e3405f1d4719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
