<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_address</name>
   <tag></tag>
   <elementGuidId>d14a9b61-c33b-4d58-9dcf-d6042b7e4d4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[16]/div/div[count(. | //div[@class = 'modal-body']) = count(//div[@class = 'modal-body'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>6526dbf8-39da-46e3-94ba-2a7689dad930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19a31dc5-5d96-49ff-b53b-233dda326bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[16]/div/div</value>
      <webElementGuid>7f35e1b2-a1f4-4ede-a085-70f4bcd6970e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
