<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cod_modal_Okay_btn</name>
   <tag></tag>
   <elementGuidId>efb31ac9-da87-430a-9bde-81b01f400e47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[16]/div/div/div[2]/button[2][count(. | //button[@type = 'button' and @class = 'btn btn-success']) = count(//button[@type = 'button' and @class = 'btn btn-success'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9a00c5d-83aa-4ebc-a53c-7ad10369f960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1dca8370-7413-4562-8fb8-76880ad866f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>f4b2c572-a3c1-490f-b0d3-179305d89368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[16]/div/div/div[2]/button[2]</value>
      <webElementGuid>10c3179f-d9f8-40ef-80a9-053a3cd31cc3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
