<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cod_modal</name>
   <tag></tag>
   <elementGuidId>0d968b27-bb82-4c4f-8210-c7a290b4d2f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[16]/div/div[count(. | //div[@class = 'modal-content']) = count(//div[@class = 'modal-content'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40088d69-e8fa-4f4a-8f13-073888e85062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-content</value>
      <webElementGuid>c859714f-2925-45f0-aafb-6fbe0aaca382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[16]/div/div</value>
      <webElementGuid>98e21c1f-39dd-4238-ba33-bad0d4c781bf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
