<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_address_button</name>
   <tag></tag>
   <elementGuidId>27c7b3c0-e27a-4373-bf00-2314bcc2b418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='ADD ADDRESS']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[4]/input[count(. | //input[@type = 'button' and @value = 'ADD ADDRESS' and @class = 'my-btn btn-black']) = count(//input[@type = 'button' and @value = 'ADD ADDRESS' and @class = 'my-btn btn-black'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.my-btn.btn-black</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8ee858d-bf43-4f4d-80a9-693e68f4d855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00d3c4e1-d468-4f82-9f2d-4691fb836b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ADD ADDRESS</value>
      <webElementGuid>41e8bb4e-0584-4cd0-8d64-d6dff4c46585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>add_address(event)</value>
      <webElementGuid>4c85314a-9148-4b5d-b568-ffcc6118ef72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-btn btn-black</value>
      <webElementGuid>f862e7b2-afea-4586-943b-4b2ffb729a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[4]/input</value>
      <webElementGuid>48b13784-117a-4c88-9c83-8ffa7e75fdeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='ADD ADDRESS']</value>
      <webElementGuid>6b9e9143-5189-4e2f-8959-5a0cc9ffe0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address-form']/div[4]/input</value>
      <webElementGuid>f09afcf4-0d65-43b4-a9b7-6039ef49f856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/input</value>
      <webElementGuid>32a4709e-2c39-4719-bcd9-09b3f44af2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>e9b034d9-9b4a-4a90-9b09-844ea2e704f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
