<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_header</name>
   <tag></tag>
   <elementGuidId>74b93687-c322-4f82-b67b-53770b28e521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address']/div/div/div/h4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/div[1]/h4[count(. | //h4[@class = 'title' and (text() = 'NEW DELIVERY ADDRESS' or . = 'NEW DELIVERY ADDRESS')]) = count(//h4[@class = 'title' and (text() = 'NEW DELIVERY ADDRESS' or . = 'NEW DELIVERY ADDRESS')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>ee9170af-9eba-4767-835b-42f048ea769b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>712c2ddf-c808-4005-bddb-4aa58a1c444b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEW DELIVERY ADDRESS</value>
      <webElementGuid>9eb4dbfa-ac85-408a-87bd-5a324cc738ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/div[1]/h4</value>
      <webElementGuid>e83b7b98-c3ac-4e7b-a02d-4402870373f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address']/div/div/div/h4</value>
      <webElementGuid>f45dd434-7105-449c-9b78-c69c89dbf918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[1]/following::h4[1]</value>
      <webElementGuid>bc34fa03-ca4f-4e92-989a-85a0a6a30456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seller Location'])[1]/following::h4[1]</value>
      <webElementGuid>82a73037-1028-45b7-9a1a-ac24b1012e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESSEE FIRST NAME'])[1]/preceding::h4[1]</value>
      <webElementGuid>1f6f5de1-d0ae-4713-a9b6-8c1bcab6fc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESSEE LAST NAME'])[1]/preceding::h4[1]</value>
      <webElementGuid>728937e0-ac55-4958-9e6a-b78920e5b201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEW DELIVERY ADDRESS']/parent::*</value>
      <webElementGuid>8a7088db-938f-4f99-bd04-03fc6953a176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>5c04fcf4-061f-47f0-9888-ceaae4a4f1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'NEW DELIVERY ADDRESS' or . = 'NEW DELIVERY ADDRESS')]</value>
      <webElementGuid>3a3b0a9c-4d86-4492-ad0d-d3cbf83696eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
