<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_lname_textlabel</name>
   <tag></tag>
   <elementGuidId>4198bf88-1e97-468e-b690-fdaf38848d71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='address-form']/div/div[2]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[1]/div[2]/label[count(. | //label[(text() = 'ADDRESSEE LAST NAME' or . = 'ADDRESSEE LAST NAME')]) = count(//label[(text() = 'ADDRESSEE LAST NAME' or . = 'ADDRESSEE LAST NAME')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>562349de-103b-4683-bc77-a01e0f3ef6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADDRESSEE LAST NAME</value>
      <webElementGuid>d7437515-bba7-48b7-afff-b7a50de31265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[1]/div[2]/label</value>
      <webElementGuid>1ef79337-8a57-4be8-b898-7d43281e4be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address-form']/div/div[2]/label</value>
      <webElementGuid>700daeb2-eb97-494a-b257-87e25e325b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESSEE FIRST NAME'])[1]/following::label[1]</value>
      <webElementGuid>70b2742c-7e94-4bca-bec0-95ccc601bec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW DELIVERY ADDRESS'])[1]/following::label[2]</value>
      <webElementGuid>f99784f1-c2a4-4316-bf1a-cc7f556f5bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESS'])[2]/preceding::label[1]</value>
      <webElementGuid>4e9b35f7-ff48-4da5-a945-4a8fd8170480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COUNTRY'])[1]/preceding::label[2]</value>
      <webElementGuid>c902e001-2883-45a4-a2da-53fff69bb721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADDRESSEE LAST NAME']/parent::*</value>
      <webElementGuid>992d7623-4709-4016-a39b-6a0fdce9891b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/div[2]/label</value>
      <webElementGuid>b6312de2-810b-45a3-b429-cc4efc43da34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'ADDRESSEE LAST NAME' or . = 'ADDRESSEE LAST NAME')]</value>
      <webElementGuid>d6d7c6d8-fdc2-49ff-a7f7-7ed67d3b5b47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
