<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_toaster</name>
   <tag></tag>
   <elementGuidId>afc5e610-528a-4d51-b027-caabbd9d90a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[16][count(. | //div[@id = 'toast-container']) = count(//div[@id = 'toast-container'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8602dca-3cdd-45d8-bec3-0b721d1e5fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-container</value>
      <webElementGuid>64ed2fd3-f1b0-4a4d-8320-75cbeb1ff3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[16]</value>
      <webElementGuid>c9311097-6c35-4663-99c2-77d4e3a93d18</webElementGuid>
   </webElementProperties>
</WebElementEntity>
