<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_header</name>
   <tag></tag>
   <elementGuidId>74b93687-c322-4f82-b67b-53770b28e521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/div[1]/h4[count(. | //h4[@class = 'title' and (text() = 'NEW DELIVERY ADDRESS' or . = 'NEW DELIVERY ADDRESS')]) = count(//h4[@class = 'title' and (text() = 'NEW DELIVERY ADDRESS' or . = 'NEW DELIVERY ADDRESS')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address']/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>6680be30-9675-4922-9195-0490d1fae015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>345af7bb-200c-4e00-bf35-49d628c4aeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEW DELIVERY ADDRESS</value>
      <webElementGuid>1bf8b3da-d4c8-4f53-8bc2-c4d13257b0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/div[1]/h4</value>
      <webElementGuid>693b1f54-a626-4921-8e20-70c23a227b20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address']/div/div/div/h4</value>
      <webElementGuid>72817025-746e-4d5d-be2a-10e0de843e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[1]/following::h4[1]</value>
      <webElementGuid>388ceff8-2c81-4376-84bb-3c21b00b402e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seller Location'])[1]/following::h4[1]</value>
      <webElementGuid>0d8fa222-2814-4386-a8b8-80174dc211fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESSEE FIRST NAME'])[1]/preceding::h4[1]</value>
      <webElementGuid>5178f6b3-e6c1-4704-b162-f95b86c2c5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESSEE LAST NAME'])[1]/preceding::h4[1]</value>
      <webElementGuid>9cd0b842-44dd-4c90-855c-2f5185f9adda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEW DELIVERY ADDRESS']/parent::*</value>
      <webElementGuid>7c87d9ca-2cab-4dd0-8a57-f45f3065c5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>e58e6e29-4a81-434e-a098-9210ad4ef9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'NEW DELIVERY ADDRESS' or . = 'NEW DELIVERY ADDRESS')]</value>
      <webElementGuid>4a9267b6-81cd-4940-a635-bf60bbb45ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
