<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addres_fname_textlabel</name>
   <tag></tag>
   <elementGuidId>2bed3e97-cae9-41c7-8b3a-e885079d9fcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='address-form']/div/div/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[1]/div[1]/label[count(. | //label[(text() = 'ADDRESSEE FIRST NAME' or . = 'ADDRESSEE FIRST NAME')]) = count(//label[(text() = 'ADDRESSEE FIRST NAME' or . = 'ADDRESSEE FIRST NAME')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.gutter-30 > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ae2c8409-4c3a-4a58-8c5b-5a34036d2f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADDRESSEE FIRST NAME</value>
      <webElementGuid>e0fdb4b4-e659-401e-949e-956f30774f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[1]/div[1]/label</value>
      <webElementGuid>0ce2970d-8250-4bc8-8e26-95da8596d5f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address-form']/div/div/label</value>
      <webElementGuid>4b0616e6-36e7-42a0-9ca2-2e4713fbdd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW DELIVERY ADDRESS'])[1]/following::label[1]</value>
      <webElementGuid>bee014bd-6a6c-4184-98e8-c73bcf5a29c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[1]/following::label[1]</value>
      <webElementGuid>6c4192f3-adc1-4704-a0f8-f84edd672b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESSEE LAST NAME'])[1]/preceding::label[1]</value>
      <webElementGuid>0d43f9a2-7f4f-43a0-8b23-3ad6fd0b2f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESS'])[2]/preceding::label[2]</value>
      <webElementGuid>f9eae2e5-e46a-4e57-aba4-8b4850dc609a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADDRESSEE FIRST NAME']/parent::*</value>
      <webElementGuid>6db7fa54-9798-41be-bc86-ec1dc30e565e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/div/label</value>
      <webElementGuid>cdd42a98-8373-44b4-9704-cdb82d9c4f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'ADDRESSEE FIRST NAME' or . = 'ADDRESSEE FIRST NAME')]</value>
      <webElementGuid>e1d48119-7cce-4c57-8a0d-c2bc135ade24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
