<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_tab</name>
   <tag></tag>
   <elementGuidId>dbbd2290-8824-4bd4-bd8f-55b3681dcf39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/ul/li[2]/a[count(. | //a[@href = '#address' and @id = 'address-tab']) = count(//a[@href = '#address' and @id = 'address-tab'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='address-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd87b6f6-b91d-484f-a011-ad80b281b730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#address</value>
      <webElementGuid>622c3a28-6586-45f6-850e-a5d4d6ee0d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-tab</value>
      <webElementGuid>798a8a59-74c4-4132-ab73-5afbe9337069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>validatePermission(&quot;view-merchant-addresses&quot;, &quot;User Addresses&quot;, &quot;Merchant&quot;); Validate('#address-tab', 1, false);</value>
      <webElementGuid>0340c4d8-3a18-4b96-8762-2fd4b5893fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/ul/li[2]/a</value>
      <webElementGuid>a8810fa0-97ae-46e7-ace6-5f77f457fb1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='address-tab']</value>
      <webElementGuid>5d17a123-2e60-4212-9779-b834e582db81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='setting-tab']/li[2]/a</value>
      <webElementGuid>f41d7ad0-b097-46a8-83d4-087994c633d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROFILE'])[2]/following::a[1]</value>
      <webElementGuid>e3591a1c-44e1-4487-b908-4897b8e49b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER SETTINGS'])[1]/following::a[2]</value>
      <webElementGuid>fddd4175-c8c7-42ec-9c11-b8f4a8d9b0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT ACCEPTANCE'])[1]/preceding::a[1]</value>
      <webElementGuid>508d4905-e60c-4b1e-862f-ff65d769f495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#address')]</value>
      <webElementGuid>51473335-5184-4363-ba4b-008d3394a64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/ul/li[2]/a</value>
      <webElementGuid>57e23cac-5d8b-40cb-8caa-67a84130bb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#address' and @id = 'address-tab' and (text() = '
                ADDRESS
            ' or . = '
                ADDRESS
            ')]</value>
      <webElementGuid>3973aa79-ee2c-495b-9304-a008aec3b232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
