<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_textbox</name>
   <tag></tag>
   <elementGuidId>cb587faa-5ffb-4d09-9370-c81e21f71603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[2]/div/input[count(. | //input[@type = 'text' and @name = 'myaddress' and @id = 'myaddress' and @class = 'required']) = count(//input[@type = 'text' and @name = 'myaddress' and @id = 'myaddress' and @class = 'required'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='myaddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#myaddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad58cfb8-bf59-4a2a-b5ff-faed9863321b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc547d21-35c2-4830-b726-a2616fbda78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>myaddress</value>
      <webElementGuid>035a19bf-25f0-49e0-a443-667a4224c5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myaddress</value>
      <webElementGuid>37991baa-dad7-4e9a-8bba-9cf446a0dc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>57e0d1df-ce3a-4b11-970e-7a9e93479060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[2]/div/input</value>
      <webElementGuid>382b8901-882b-4930-94f5-1146f5fbd012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myaddress']</value>
      <webElementGuid>8ec2b4ad-884f-4cdc-b5a2-c27b74abbd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address-form']/div[2]/div/input</value>
      <webElementGuid>0dca9b48-8f85-49eb-9440-5e4dce4542df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div[2]/div/input</value>
      <webElementGuid>baf13544-8c3a-4370-a56e-f5ac2c35d872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'myaddress' and @id = 'myaddress']</value>
      <webElementGuid>1a7c0de8-2e1b-4bb0-880a-2f709517ae44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
