<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_tab</name>
   <tag></tag>
   <elementGuidId>dbbd2290-8824-4bd4-bd8f-55b3681dcf39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='address-tab']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/ul/li[2]/a[count(. | //a[@href = '#address' and @id = 'address-tab']) = count(//a[@href = '#address' and @id = 'address-tab'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f128bd48-8c81-4362-859e-5c7b8f950db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#address</value>
      <webElementGuid>8518ada4-aa19-43a8-b0c1-ddecf7692d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-tab</value>
      <webElementGuid>7e864297-1268-42a1-9b1f-9a10bb0fd844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>validatePermission(&quot;view-merchant-addresses&quot;, &quot;User Addresses&quot;, &quot;Merchant&quot;); Validate('#address-tab', 1, false);</value>
      <webElementGuid>09c1fe3a-cc18-4a4f-a473-94907cdf64f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/ul/li[2]/a</value>
      <webElementGuid>b642f732-2402-460f-b3d9-7a88c8825dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='address-tab']</value>
      <webElementGuid>3cc3f683-0200-4834-a8a9-02b202ead329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='setting-tab']/li[2]/a</value>
      <webElementGuid>8d5ad30a-9a57-4e71-a82f-a76335d3e693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROFILE'])[2]/following::a[1]</value>
      <webElementGuid>19f29294-9eb8-480a-9d13-e2cb4e7f5579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER SETTINGS'])[1]/following::a[2]</value>
      <webElementGuid>ae1f1f86-56b4-4387-927b-a48ff51b9619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT ACCEPTANCE'])[1]/preceding::a[1]</value>
      <webElementGuid>5ed327fc-164a-4504-b632-350bb992127c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#address')]</value>
      <webElementGuid>575f43dd-f56d-44c7-b6e9-82d2046822dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/ul/li[2]/a</value>
      <webElementGuid>1bbb8289-fa6c-4f15-bdf8-ce2c0b7ba91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#address' and @id = 'address-tab' and (text() = '
                ADDRESS
            ' or . = '
                ADDRESS
            ')]</value>
      <webElementGuid>840c247f-d402-431d-a2ae-670ac1eae88a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
