<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_textbox</name>
   <tag></tag>
   <elementGuidId>cb587faa-5ffb-4d09-9370-c81e21f71603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='myaddress']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[2]/div/input[count(. | //input[@type = 'text' and @name = 'myaddress' and @id = 'myaddress' and @class = 'required']) = count(//input[@type = 'text' and @name = 'myaddress' and @id = 'myaddress' and @class = 'required'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#myaddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1837324b-5fad-4f27-ae24-e2407b6db6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1eea9366-0c8f-4fd1-99c0-0956c79ef981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>myaddress</value>
      <webElementGuid>e4c3f3f0-feea-4b89-8309-3f6da355f0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myaddress</value>
      <webElementGuid>cb3aed2f-d399-4edb-bb2b-815c58cc5c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9cdd2364-0873-45d3-bf35-b94b1a174bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[2]/div/input</value>
      <webElementGuid>1c150434-78bc-4a85-8fe8-f0f070bf5b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myaddress']</value>
      <webElementGuid>b85474db-508f-45de-92df-f6c3a1e74d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='address-form']/div[2]/div/input</value>
      <webElementGuid>c2221d6c-0e5b-4d2f-a4ad-00fe600361e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div[2]/div/input</value>
      <webElementGuid>33435db2-b8bd-4855-bd7d-2b0a123e12d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'myaddress' and @id = 'myaddress']</value>
      <webElementGuid>70970b14-1021-42ae-b9dd-6e54b59c630a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
