<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_container_1</name>
   <tag></tag>
   <elementGuidId>13eb8245-8391-48d5-9f0c-eeae70323768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address']/div/div[2]/div[3]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.description</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;address&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;seller-common-box&quot;]/div[@class=&quot;address-inner&quot;]/div[@class=&quot;col-md-4 col-sm-4 gutter-30&quot;]/div[@class=&quot;address-box&quot;]/div[@class=&quot;description&quot;][count(. | //div[@class = 'description']) = count(//div[@class = 'description'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5da5031-e078-45b2-ab9e-2227865a051f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>99577e2f-286e-4734-9ccf-f32009775003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test testtestAlbaniatesttesttest</value>
      <webElementGuid>11abbd7e-51b5-467c-978d-bb788b9a79e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div[3]/div[1]/div/div[1]</value>
      <webElementGuid>8600abaf-d30a-4ea1-8e8d-ea933c4c85a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address']/div/div[2]/div[3]/div/div/div</value>
      <webElementGuid>38e373fc-d38e-46ae-9739-f1e2f6a7ab0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVED ADDRESSES'])[1]/following::div[5]</value>
      <webElementGuid>92325588-5c71-4c68-8443-cbc9b28aa3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POSTAL CODE'])[1]/following::div[8]</value>
      <webElementGuid>fbea3c2e-0839-412a-9c99-db9ace2aa0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[2]/preceding::div[4]</value>
      <webElementGuid>468387e7-d813-4a5e-827b-c8ecad15eff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/preceding::div[5]</value>
      <webElementGuid>dc6e1c10-0f40-4ecf-8bf0-18f14a0d3483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test test']/parent::*</value>
      <webElementGuid>7f69b05f-e44b-4625-a9d1-eb796abf4917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div</value>
      <webElementGuid>5cdbf816-cac6-4157-93fd-3f21bd1781e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'test testtestAlbaniatesttesttest' or . = 'test testtestAlbaniatesttesttest')]</value>
      <webElementGuid>482e6265-4d6f-4c94-8e42-f461a2344c39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
