<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cash_delivery_textlabel</name>
   <tag></tag>
   <elementGuidId>f4b50725-2693-47e3-93c4-1b446a1a08c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[1]/div/div/b[count(. | //b[(text() = 'Cash on delivery' or . = 'Cash on delivery')]) = count(//b[(text() = 'Cash on delivery' or . = 'Cash on delivery')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment_acceptance']/div/div/div/div[2]/div/div/div/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cash-on-delivery-container > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>da45db54-4995-4e96-b612-8ba292be6366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cash on delivery</value>
      <webElementGuid>8efdfb4a-82ca-405a-b0fb-8afdd9c8d334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[1]/div/div/b</value>
      <webElementGuid>f974e262-e7e0-4cf4-84c5-7b68669e9f2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment_acceptance']/div/div/div/div[2]/div/div/div/b</value>
      <webElementGuid>fd54a590-bb48-4240-9d0c-f648740453b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/following::b[1]</value>
      <webElementGuid>9a90bfa6-e699-4101-9fcf-26021104dc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[2]/following::b[2]</value>
      <webElementGuid>4adc157d-c07e-4f54-8a9d-5434229fbd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No account linked yet'])[1]/preceding::b[1]</value>
      <webElementGuid>be8569d4-9a14-47a6-9645-e2c404cb47e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Account'])[1]/preceding::b[1]</value>
      <webElementGuid>6174e314-4957-4afc-b34b-b6df9b31f1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cash on delivery']/parent::*</value>
      <webElementGuid>d8e82790-1a9c-48af-bff9-14532916e79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/b</value>
      <webElementGuid>d59a0593-3d15-4d6c-9999-a5eda4446d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Cash on delivery' or . = 'Cash on delivery')]</value>
      <webElementGuid>ff079050-5cf8-441b-962c-974e5c38dffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
