<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>change_button</name>
   <tag></tag>
   <elementGuidId>55ab7f32-94a6-42a5-b047-5a11856d124c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[1]/div/div/div[2]/a[count(. | //a[@href = '#' and @data-callback = 'saveUserPhoto' and @class = 'my-btn btn-black model-btn']) = count(//a[@href = '#' and @data-callback = 'saveUserPhoto' and @class = 'my-btn btn-black model-btn'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profile']/div/div/form/div/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.my-btn.btn-black.model-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04545e76-2286-4fa5-a94f-72d4b06eb652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ddd2d8a6-4cb7-433c-85f7-3df9719801ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>b3f491b2-0d48-468d-ba60-a379f1b6d9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>7f18244c-df82-4758-be0f-71fed656865c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#_1_1_imagecropperModal</value>
      <webElementGuid>25541a27-4141-4a07-942f-1a324230266b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-callback</name>
      <type>Main</type>
      <value>saveUserPhoto</value>
      <webElementGuid>349c425b-98a2-4532-840c-1beeee6ff69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-btn btn-black model-btn</value>
      <webElementGuid>e68c81ea-c95e-4419-ad1c-0f7b9e5fa59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>98c0c545-0be1-4d32-80b3-83937e989728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>You need permission to perform this action</value>
      <webElementGuid>e26ea2a4-5675-4284-99ea-a6092d559b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHANGE</value>
      <webElementGuid>413156ad-f853-4dc3-99ee-b0b4fcd4a526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[1]/div/div/div[2]/a</value>
      <webElementGuid>b604d821-0bb6-4422-bd93-2d2593fad5d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div/div/div/div[2]/a</value>
      <webElementGuid>dce71bb1-f0ac-40d4-994f-01b25a3013c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CHANGE')]</value>
      <webElementGuid>222baae9-8082-4a08-9f9f-e80ebe839d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT ACCEPTANCE'])[1]/following::a[1]</value>
      <webElementGuid>d79a387a-218e-4e58-b441-fb1105306ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISPLAY NAME'])[1]/preceding::a[1]</value>
      <webElementGuid>63a022f6-4981-4a70-8316-a62b7fe6e788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESCRIPTION'])[1]/preceding::a[1]</value>
      <webElementGuid>ea75a016-6f0b-4e31-9a4b-c4e185327db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CHANGE']/parent::*</value>
      <webElementGuid>93f64fbd-a1c5-461a-bcbd-16cffdb31879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>5eedb559-5a2b-40d1-9d78-f64061528514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/a</value>
      <webElementGuid>cd5d2353-03f2-4fa9-a9f7-3c87525248e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
                                            CHANGE
                                        ' or . = '
                                            CHANGE
                                        ')]</value>
      <webElementGuid>ea8b39a3-9269-428e-9abe-7096d0429ebd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
