<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_textlabel</name>
   <tag></tag>
   <elementGuidId>8c2eba68-d34b-411f-8602-e17572967885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[3]/div[3]/label[count(. | //label[(text() = 'CITY' or . = 'CITY')]) = count(//label[(text() = 'CITY' or . = 'CITY')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address-fields']/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7626c6e0-2f56-4f3a-9f80-4f97e22b130f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CITY</value>
      <webElementGuid>a98a7d68-0916-4526-8c1e-ec1e8642fb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[3]/div[3]/label</value>
      <webElementGuid>224db6fb-db22-4a8b-88d5-a8648efe2dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-fields']/div[3]/label</value>
      <webElementGuid>87a5787b-42b1-4493-904d-e35fd607a107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STATE'])[1]/following::label[1]</value>
      <webElementGuid>554990c9-9ece-48dc-bca2-51e2bd4e25fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COUNTRY'])[1]/following::label[2]</value>
      <webElementGuid>62a73355-6143-457d-8781-2e58fb401e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POSTAL CODE'])[1]/preceding::label[1]</value>
      <webElementGuid>b41a5cfc-1608-4a54-9e8d-9464db50eb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVED ADDRESSES'])[1]/preceding::label[2]</value>
      <webElementGuid>c1aca2b3-3c01-411e-b439-c389c10d430a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CITY']/parent::*</value>
      <webElementGuid>a34721c1-344f-4948-b0f2-9a61ed0a8e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label</value>
      <webElementGuid>aba94244-11f5-484d-a805-dddc06be2800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'CITY' or . = 'CITY')]</value>
      <webElementGuid>c013521a-100e-4180-b831-00c43cf44bc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
