<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contact_number_textbox</name>
   <tag></tag>
   <elementGuidId>ece100a4-a8f9-4533-bd7f-a5dd76a53b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-contactNumber&quot;)[count(. | //input[@type = 'text' and @class = 'required phoneOnly' and @name = 'PhoneNumber' and @id = 'input-contactNumber']) = count(//input[@type = 'text' and @class = 'required phoneOnly' and @name = 'PhoneNumber' and @id = 'input-contactNumber'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-contactNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-contactNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a40072c-487f-468b-9df1-8069d7710ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea9c8d85-3074-4842-a772-1b644295136f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required phoneOnly</value>
      <webElementGuid>eaa83443-50d5-4ac5-b061-551ecb9e23b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>fa6a8532-1665-4afa-8892-feccfec23130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-contactNumber</value>
      <webElementGuid>b869e78d-15ce-4905-8438-c9e1ea9bffa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-contactNumber&quot;)</value>
      <webElementGuid>294ab6b0-cdfc-40cd-960d-797e26c0c54a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-contactNumber']</value>
      <webElementGuid>32d2e08d-004d-4413-b6c8-eb9e3650e150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[5]/div[2]/input</value>
      <webElementGuid>ff7ee6da-efad-4486-a0d9-a6822081ea4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>66abd497-dd7f-4779-a714-1a9da10bbcdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'PhoneNumber' and @id = 'input-contactNumber']</value>
      <webElementGuid>08a0e841-a3a9-4ada-a1f8-67d373d2c94a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
