<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contact_number_textbox</name>
   <tag></tag>
   <elementGuidId>ece100a4-a8f9-4533-bd7f-a5dd76a53b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-contactNumber']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[2]/input[count(. | //input[@type = 'text' and @class = 'required phoneOnly' and @name = 'PhoneNumber']) = count(//input[@type = 'text' and @class = 'required phoneOnly' and @name = 'PhoneNumber'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-contactNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8306e317-b772-49de-b461-f5ba93566f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fba331ec-8afc-4acd-84a2-edf2c94484ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required phoneOnly</value>
      <webElementGuid>526bec87-847d-4598-8179-f6627a38bf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>3b2953f7-5d35-4991-9a69-282f85c8678a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-contactNumber</value>
      <webElementGuid>4f3e8ed1-6a65-40e1-8731-a352d40cc88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[2]/input</value>
      <webElementGuid>35351cd2-83f6-4460-8453-046d3aa428ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-contactNumber']</value>
      <webElementGuid>354865a1-58b9-4f56-bd01-88c06d6c67e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[5]/div[2]/input</value>
      <webElementGuid>76d1eb41-3d1d-4e57-9348-b81668cc4f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>93d07116-a9b3-4a1a-973d-c4ee6a9eaae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'PhoneNumber' and @id = 'input-contactNumber']</value>
      <webElementGuid>a7e52317-f709-4e01-8e1f-350e3edc961d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
