<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contact_number_textbox</name>
   <tag></tag>
   <elementGuidId>ece100a4-a8f9-4533-bd7f-a5dd76a53b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-contactNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-contactNumber']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[2]/input[count(. | //input[@type = 'text' and @class = 'required phoneOnly' and @name = 'PhoneNumber']) = count(//input[@type = 'text' and @class = 'required phoneOnly' and @name = 'PhoneNumber'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f449874-f26d-4eab-8e37-1ff68cd535ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32b37bb1-b0d9-4bae-bd7f-a6e01eb71c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required phoneOnly</value>
      <webElementGuid>e22c91ba-0337-429d-8968-2609ab101f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>481cea19-83ee-4409-b9a5-5eaed3512a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-contactNumber</value>
      <webElementGuid>f0182516-e0c4-4e38-ad1e-f7dae8bdefff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[2]/input</value>
      <webElementGuid>7eeb235b-62fd-45d3-bbba-8ab683e4b9c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-contactNumber']</value>
      <webElementGuid>565769c5-0549-49a7-9a55-0ea418ebb0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[5]/div[2]/input</value>
      <webElementGuid>95cc21fc-1d5a-4cdc-9acb-704961eaeb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>b013f15f-00c7-4fc1-a0cc-51cd0af35cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'PhoneNumber' and @id = 'input-contactNumber']</value>
      <webElementGuid>54e34785-33f2-4872-b4bc-cd5cce4665fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
