<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_textlabel</name>
   <tag></tag>
   <elementGuidId>1c18da35-8437-410a-bc4a-be5cb3762893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address-fields']/div/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[3]/div[1]/label[count(. | //label[(text() = 'COUNTRY' or . = 'COUNTRY')]) = count(//label[(text() = 'COUNTRY' or . = 'COUNTRY')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-fields > div.col-md-6.gutter-30 > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>02857eeb-b1b9-4963-9cdf-896c6c496c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COUNTRY</value>
      <webElementGuid>21c76d38-ff2b-40b0-ae72-bf6755716a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[3]/div[1]/label</value>
      <webElementGuid>b8b101ab-16c6-4a3a-8c56-7fab5c42b0b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-fields']/div/label</value>
      <webElementGuid>fe1ca4b4-80b7-400e-a3af-8380a4d6bdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESS'])[2]/following::label[1]</value>
      <webElementGuid>dae26861-febe-4352-9c83-d3b6a381f96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESSEE LAST NAME'])[1]/following::label[2]</value>
      <webElementGuid>01f19eb3-2a42-4262-a07e-7381d7eca9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STATE'])[1]/preceding::label[1]</value>
      <webElementGuid>4612cef2-224e-431a-b9df-52e348a62bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CITY'])[1]/preceding::label[2]</value>
      <webElementGuid>3a80715d-1770-4032-aa37-e4a29aa03899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COUNTRY']/parent::*</value>
      <webElementGuid>33b5d8db-422c-45db-a02c-abc39713ad2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div[3]/div/label</value>
      <webElementGuid>cef589b1-cede-4572-af33-15fb1e58c45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'COUNTRY' or . = 'COUNTRY')]</value>
      <webElementGuid>83aa1bfe-6bbe-4f59-99fb-e3f0dfae4494</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
