<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete_address_button_1</name>
   <tag></tag>
   <elementGuidId>3ad11da4-123d-414e-bf7f-b90977ba3b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='120877']/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div[3]/div[1]/div/div[2]/a/i[count(. | //i[@class = 'icon icon-remove']) = count(//i[@class = 'icon icon-remove'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.icon-remove</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bfa0b434-fe56-408d-a902-645ffbabc89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-remove</value>
      <webElementGuid>87341f25-577c-45b3-84e4-cbb656f0051c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div[3]/div[1]/div/div[2]/a/i</value>
      <webElementGuid>a54c32bb-b0bd-4ff9-918c-5a7c3da2bdb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='120877']/i</value>
      <webElementGuid>e1938370-aad7-4d91-94ac-b7b52ffa2c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>5305939b-5c17-47ce-8e99-25a810561365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
