<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>description_textbox</name>
   <tag></tag>
   <elementGuidId>ab2f4044-6e1b-4006-90d2-06a03d190792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-description']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-description&quot;)[count(. | //textarea[@name = 'description' and @id = 'input-description' and @class = 'big-text-area']) = count(//textarea[@name = 'description' and @id = 'input-description' and @class = 'big-text-area'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a7fee452-80fa-44d2-9641-f68299721ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>15e947b4-a481-4c4c-acc1-e2ac28e566bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-description</value>
      <webElementGuid>7986ace3-feb1-48a5-8f37-a2f7bf5e6e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>big-text-area</value>
      <webElementGuid>d7166f39-7f06-4e08-8cc9-b94642d43d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-description&quot;)</value>
      <webElementGuid>cb4db3d3-73d0-4de8-8d25-b314c344463e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-description']</value>
      <webElementGuid>4fa0e01c-d6a9-415c-8a3e-d6434274c744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[3]/div/textarea</value>
      <webElementGuid>1302fdcb-7d77-478b-b53f-c2fcac0152d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>40a6560f-bed6-4896-8834-66c5153f2713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'input-description']</value>
      <webElementGuid>abe56a5e-3714-4de1-a9c0-281d022d1c21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
