<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>description_textbox</name>
   <tag></tag>
   <elementGuidId>ab2f4044-6e1b-4006-90d2-06a03d190792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-description&quot;)[count(. | //textarea[@name = 'description' and @id = 'input-description' and @class = 'big-text-area']) = count(//textarea[@name = 'description' and @id = 'input-description' and @class = 'big-text-area'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b64f7584-fc70-41df-95f6-c8d4c232e19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>9208cd89-51e5-4077-8110-6bfc4ce6801f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-description</value>
      <webElementGuid>f6a85c29-5a53-48fc-94ab-72a4c20dfc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>big-text-area</value>
      <webElementGuid>0da597a9-5088-44ce-bffb-b905876adf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-description&quot;)</value>
      <webElementGuid>e77b8ac0-69e1-4f3b-a841-1d6aca724d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-description']</value>
      <webElementGuid>a7a704d6-0b59-4c68-ae20-73f9f557122d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[3]/div/textarea</value>
      <webElementGuid>3654a33b-0f7b-4633-b00b-8d6471dcf616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c949af68-4c9b-4ffd-bee6-ae90c8b3dcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'input-description']</value>
      <webElementGuid>8516ed8b-06f7-4dce-8064-866354062e3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
