<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>display_name_textbox</name>
   <tag></tag>
   <elementGuidId>a213cda7-d2f9-4d73-8e27-a67e999d1447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-displayName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-displayName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @id = 'input-displayName' and @class = 'required']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>525626b5-dae7-4c0d-a49e-ad9621fa0cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d078b897-959d-4ac9-99ac-9b7ddfd9160f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DisplayName</value>
      <webElementGuid>864cc6ee-8b9e-4f70-95c8-6b42335f8f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-displayName</value>
      <webElementGuid>6f6ca397-f5a5-4869-9b86-cb4e5e31ed25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>774e7c42-5ba4-4bf4-a1f4-748a01809380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[2]/div/input</value>
      <webElementGuid>be842093-fafc-48aa-a8ec-79a590507bdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-displayName']</value>
      <webElementGuid>3696dd12-0fa9-4f97-ba6d-3a7c3c85bdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[2]/div/input</value>
      <webElementGuid>1e00b32a-a72e-423a-8f68-50b471e36030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/input</value>
      <webElementGuid>8bbabf74-066f-4761-b839-b11f9953acaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DisplayName' and @id = 'input-displayName']</value>
      <webElementGuid>eea5eacb-2c61-4891-a3ab-d76c220226fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
