<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>display_name_textbox</name>
   <tag></tag>
   <elementGuidId>a213cda7-d2f9-4d73-8e27-a67e999d1447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-displayName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-displayName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[2]/div/input[count(. | //input[@type = 'text' and @id = 'input-displayName' and @class = 'required']) = count(//input[@type = 'text' and @id = 'input-displayName' and @class = 'required'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ae317ed-5eb5-4424-911b-7f166d197bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>649bd2ec-f7d0-4429-a3db-3ad3f56b93d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DisplayName</value>
      <webElementGuid>24b927cc-bd01-4004-a90b-de77e7b7180d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-displayName</value>
      <webElementGuid>150ae600-2d55-4337-bff8-805975a202ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d72d2bae-ddc5-4598-9a04-e1c65fb9db45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[2]/div/input</value>
      <webElementGuid>ed490117-b53f-4b8c-b657-7cb7df5d1e6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-displayName']</value>
      <webElementGuid>f4c41a9a-e84b-4fe3-b44c-3f535aa622e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[2]/div/input</value>
      <webElementGuid>b15adb82-cb34-485d-b00a-a117fe0fe85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/input</value>
      <webElementGuid>79f2db60-aeb2-4511-bd98-5dfab6a6a3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DisplayName' and @id = 'input-displayName']</value>
      <webElementGuid>8c50dd03-fce2-4861-b66d-5d36506c3e99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
