<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_txtbox</name>
   <tag></tag>
   <elementGuidId>721c0fef-b4a1-46e2-a99e-48e56288f2c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/input[count(. | //input[@type = 'text' and @class = 'required emailOnly' and @id = 'notification-email' and @name = 'Email']) = count(//input[@type = 'text' and @class = 'required emailOnly' and @id = 'notification-email' and @name = 'Email'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notification-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notification-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c69c08f6-2678-4cdc-b0ef-d7f6a18d0c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d65fc10-18cb-4622-8fa7-62f02a08b7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required emailOnly</value>
      <webElementGuid>59208c55-fae3-430c-b214-864c8760c5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notification-email</value>
      <webElementGuid>e6b22745-e288-4ff6-a78d-8103e8b88965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>2079ecd7-4b41-48e5-956f-53bf064d5a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kentest06+bespokeautomationmerchant1@gmail.com</value>
      <webElementGuid>640753ec-a82b-4ff9-a786-bdbfce831443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/input</value>
      <webElementGuid>15b00cc4-7f07-49af-ba4d-3a616b1b2dc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notification-email']</value>
      <webElementGuid>b5d049fd-cf8b-49f4-9420-05725405f2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[5]/div/input</value>
      <webElementGuid>1cbca76e-9d8d-4c70-9e5d-4c8c3b860ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>8ccb77bf-4fdb-4334-833a-6f834abbdc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'notification-email' and @name = 'Email']</value>
      <webElementGuid>15d30c96-3db9-4c44-8656-cb0b3ef52b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
