<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_txtbox</name>
   <tag></tag>
   <elementGuidId>721c0fef-b4a1-46e2-a99e-48e56288f2c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notification-email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/input[count(. | //input[@type = 'text' and @class = 'required emailOnly' and @name = 'Email']) = count(//input[@type = 'text' and @class = 'required emailOnly' and @name = 'Email'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notification-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a9ab358-148a-4829-b103-eadc8c17566f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>420d4281-d2d2-422f-b53f-272d9276e8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required emailOnly</value>
      <webElementGuid>e91717be-553c-4120-a1f4-ad250db05110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notification-email</value>
      <webElementGuid>b43ddb87-2fa6-4802-8b6f-6d7bef67eb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>06045add-8e36-42b2-918e-89e0fccf7d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kentest06+bespokeautomationmerchant1@gmail.com</value>
      <webElementGuid>21a8d494-2413-43a5-ae28-18e59b3fdf20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/input</value>
      <webElementGuid>9783e15e-fb61-4841-a45f-94dfa7255b1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notification-email']</value>
      <webElementGuid>2b286e9b-bd65-41e8-b3bc-c4e8ace176fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[5]/div/input</value>
      <webElementGuid>1de24efb-b029-4c03-84bc-daa52d86a3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>de2d056b-212d-4094-9260-5dc07e991557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'notification-email' and @name = 'Email']</value>
      <webElementGuid>d613af73-a86c-466e-85aa-cd26dbbcab65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
