<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_txtbox</name>
   <tag></tag>
   <elementGuidId>721c0fef-b4a1-46e2-a99e-48e56288f2c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notification-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notification-email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/input[count(. | //input[@type = 'text' and @class = 'required emailOnly' and @name = 'Email']) = count(//input[@type = 'text' and @class = 'required emailOnly' and @name = 'Email'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>738fb98a-d32a-41fa-8379-739de4285657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ccb65c6-e68b-4f81-a2ce-2e111f1b85ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required emailOnly</value>
      <webElementGuid>3756921b-a92b-4fe5-8021-86ee2e6e9842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notification-email</value>
      <webElementGuid>9b8ec6b4-d82d-40ee-9fce-74d4c91fda4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>c6ce7ee4-c2c5-4917-8c81-5ce6fe57e88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kentest06+bespokeautomationmerchant1@gmail.com</value>
      <webElementGuid>6369d3d8-47e1-48b1-a7a1-bc9999ef0726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/input</value>
      <webElementGuid>42f4a8ec-ff70-4d16-9e58-16e4c881bbf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notification-email']</value>
      <webElementGuid>06bec70c-e66f-4231-aa18-b4f057e98a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[5]/div/input</value>
      <webElementGuid>18cec50f-9dc9-495f-9fa7-d526b5ef7e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>f54bcb2d-9244-40ab-966e-38286620b1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'notification-email' and @name = 'Email']</value>
      <webElementGuid>359aaf32-b5aa-4412-85aa-8f882c47c6d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
