<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fname_textbox</name>
   <tag></tag>
   <elementGuidId>ececd329-42f0-4f46-bc52-762d443a5331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-firstName&quot;)[count(. | //input[@type = 'text' and @name = 'FirstName' and @class = 'required' and @id = 'input-firstName']) = count(//input[@type = 'text' and @name = 'FirstName' and @class = 'required' and @id = 'input-firstName'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-firstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-firstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4cc791a-a94d-4f9e-9531-dc3aaf86b801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3492ec45-6f22-4df3-b9da-be2297d06fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>28f7f6f1-7fe7-45af-8548-c426e87c1f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ae4a90f1-ff12-4be3-97d3-a2a98cf59310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-firstName</value>
      <webElementGuid>179d1dfc-5927-4d5b-a0e7-c78fdc3a0eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-firstName&quot;)</value>
      <webElementGuid>1cee474e-13f0-4be8-9880-b8d7903dfe1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-firstName']</value>
      <webElementGuid>0c36e046-d170-4675-aa6b-6cf2de097bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[4]/div/input</value>
      <webElementGuid>03590a0a-a141-48e9-aaa6-11cea4b698e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div/input</value>
      <webElementGuid>a8b9bd78-14a3-446d-9aed-4dba2b481fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'FirstName' and @id = 'input-firstName']</value>
      <webElementGuid>01b069ab-ab56-46a2-8de2-b5115ca5d9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
