<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_field</name>
   <tag></tag>
   <elementGuidId>6a1889a4-3be1-4c62-b73c-9e8c0683d5f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='user-photo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[1]/div/div/div[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>799ada71-7d5a-4025-9c9c-68559319adea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-photo</value>
      <webElementGuid>45966325-41d9-4a0e-b534-53e1b6767d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/areas/user/assets/account/images/default_user.svg</value>
      <webElementGuid>e4754caa-f3ce-41a3-a0ae-976ea263786d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[1]/div/div/div[1]/img</value>
      <webElementGuid>c4c6e20f-de9d-4071-8187-c8f2da06ba5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='user-photo']</value>
      <webElementGuid>ee736030-856f-4e5a-a4d4-e8992f6cd59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div/div/div/div/img</value>
      <webElementGuid>9a4dad5d-9ca8-47d2-bac9-41472cc9dbdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>198fc61c-5151-4f72-9046-1ff69917a365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'user-photo' and @src = '/areas/user/assets/account/images/default_user.svg']</value>
      <webElementGuid>2269158b-8902-445d-b704-a780ebb89a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
