<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_field</name>
   <tag></tag>
   <elementGuidId>6a1889a4-3be1-4c62-b73c-9e8c0683d5f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[1]/div/div/div[1]/img[count(. | //img[@id = 'user-photo']) = count(//img[@id = 'user-photo'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='user-photo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user-photo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>edc21f7e-6af6-4a5d-a7e6-dc6424f89710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-photo</value>
      <webElementGuid>e8a41800-1d7a-45ba-a23c-b1699d9d4bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/areas/user/assets/account/images/default_user.svg</value>
      <webElementGuid>0c7df558-38c3-4b8c-b349-e0e6eb66f28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[1]/div/div/div[1]/img</value>
      <webElementGuid>43338fe9-19a7-44d8-88a2-6a59c14cd2e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='user-photo']</value>
      <webElementGuid>d1b85d0f-0b4b-40dd-8ffd-3e2e29314612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div/div/div/div/img</value>
      <webElementGuid>458d4893-3ef0-434a-b6c6-d4d98855750a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>ee0c2762-2ed8-4fa0-8a6c-f0ae1d6effd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'user-photo' and @src = '/areas/user/assets/account/images/default_user.svg']</value>
      <webElementGuid>5f3fa487-0843-46b9-8a3b-028683db9eae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
