<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_cropper_container</name>
   <tag></tag>
   <elementGuidId>cfe18cd2-3313-4a41-85c6-c5af4912496b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[6]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>html5imageupload modaldialog</value>
      <webElementGuid>37a5dc69-3780-4833-b793-7facb30f0c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[6]/div/div/div/div</value>
      <webElementGuid>443b7168-fca2-47c6-8ff8-3c0ff7a03665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a1a37ae-cdef-4b40-b99e-ce63d0879712</webElementGuid>
   </webElementProperties>
</WebElementEntity>
