<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_account_button</name>
   <tag></tag>
   <elementGuidId>a02aef1c-1d74-407a-8328-1035b323b81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='15712-cash-on-delivery-cash-on-delivery2yqwr1tsnco1pi0nife6']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[3]/div[count(. | //div[@id = '15712-cash-on-delivery-cash-on-delivery2yqwr1tsnco1pi0nife6' and @class = 'btn-link-payment']) = count(//div[@id = '15712-cash-on-delivery-cash-on-delivery2yqwr1tsnco1pi0nife6' and @class = 'btn-link-payment'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#15712-cash-on-delivery-cash-on-delivery2yqwr1tsnco1pi0nife6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7d1e0451-368b-4aa6-a9fb-315ea8b2df31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>15712-cash-on-delivery-cash-on-delivery2yqwr1tsnco1pi0nife6</value>
      <webElementGuid>9a429c85-eb2b-4d59-9a80-7e4b134f519a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>linkpayment</value>
      <webElementGuid>ddd57a41-c95a-4fb4-b3c9-9f043ac63b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-description</name>
      <type>Main</type>
      <value>By verifying this payment method, all your buyers will be able to checkout your items using Cash on Delivery and settlement has to be handled by you manually if they were to use this payment method.</value>
      <webElementGuid>dde43d1c-026c-4fe5-bf45-4d52d5710909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-link-payment</value>
      <webElementGuid>50ffa400-b3d3-4ae8-ab4b-c88644e893d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Link Account
                                            </value>
      <webElementGuid>cdde56ab-9a12-4827-9116-ca519084dc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[3]/div</value>
      <webElementGuid>ebcac15c-e5f0-47eb-852b-8818f7302e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='15712-cash-on-delivery-cash-on-delivery2yqwr1tsnco1pi0nife6']</value>
      <webElementGuid>010b21db-5947-4ee4-afb6-454d7dd33e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment_acceptance']/div/div/div/div[2]/div[3]/div</value>
      <webElementGuid>02a325de-e3dc-423c-90d5-2bfccf30ef10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No account linked yet'])[1]/following::div[2]</value>
      <webElementGuid>57ef7d06-1aae-4dc0-8c95-541d674afe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash on delivery'])[1]/following::div[4]</value>
      <webElementGuid>c7dc5fd0-b936-4cb7-8fd1-3f85ea770b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This payment method is compulsory.'])[1]/preceding::div[2]</value>
      <webElementGuid>f62cfb14-5ae2-45e1-b2aa-f482634d6a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::div[3]</value>
      <webElementGuid>3735eddd-8555-475c-85dd-c4f1a94a96f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link Account']/parent::*</value>
      <webElementGuid>ffabcb21-69d5-485f-8622-7664f8fe955f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[3]/div</value>
      <webElementGuid>9ec3b8b0-4d66-476f-851c-bb4148a00258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '15712-cash-on-delivery-cash-on-delivery2yqwr1tsnco1pi0nife6' and @name = 'linkpayment' and (text() = '
                                                Link Account
                                            ' or . = '
                                                Link Account
                                            ')]</value>
      <webElementGuid>3dbbec44-6bd4-4c3b-ada8-fef9aa58f38c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
