<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lname_textbox</name>
   <tag></tag>
   <elementGuidId>ab5748a9-fee3-4e81-928b-35156a723a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-lastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-lastName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[4]/div[2]/input[count(. | //input[@type = 'text' and @class = 'required' and @name = 'LastName']) = count(//input[@type = 'text' and @class = 'required' and @name = 'LastName'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b379e85e-f07d-4718-8cc8-f0f1a7979460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>baab53f8-055a-496e-baad-fe5ec6f1ad0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ed8ccf85-0d2d-48d8-bf34-66a2456d7218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>7cec409e-8b5a-44ae-8785-4cfb4de676b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-lastName</value>
      <webElementGuid>ea94e1de-47e6-4dec-9432-dcaf9a7a94c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[4]/div[2]/input</value>
      <webElementGuid>3554406d-e208-4dc4-8006-f5f3e3941cd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-lastName']</value>
      <webElementGuid>dcec3e42-3dd5-435c-ac5b-a5eb560bec0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[4]/div[2]/input</value>
      <webElementGuid>fc729694-6fc4-4642-9c31-ca9c227ce82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>0c4b9c49-3118-410a-8500-8fbc05e653eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'LastName' and @id = 'input-lastName']</value>
      <webElementGuid>9381aced-85f9-4682-a0c9-19e7b298e589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
