<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lname_textbox</name>
   <tag></tag>
   <elementGuidId>ab5748a9-fee3-4e81-928b-35156a723a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-lastName&quot;)[count(. | //input[@type = 'text' and @class = 'required' and @name = 'LastName' and @id = 'input-lastName']) = count(//input[@type = 'text' and @class = 'required' and @name = 'LastName' and @id = 'input-lastName'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-lastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-lastName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4981d93a-931f-4bb5-aa67-3e1925992dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae81388a-91df-43aa-ab7c-255ee77a2a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6205ba8f-cbac-4e26-b2f0-1b2a45d7e635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LastName</value>
      <webElementGuid>729103c6-61b6-4736-8141-016435832869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-lastName</value>
      <webElementGuid>f53c771f-53c0-49cb-b251-3628e9432249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-lastName&quot;)</value>
      <webElementGuid>ba4541fe-fb92-4aa0-9d4f-97a9116afc50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-lastName']</value>
      <webElementGuid>15856b97-008e-4700-9b8a-d1e3bfabbb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[4]/div[2]/input</value>
      <webElementGuid>f3bace62-ac0f-423b-99dd-4d73db0f5deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>4528568d-d6c1-4076-ba38-15a2e850614d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'LastName' and @id = 'input-lastName']</value>
      <webElementGuid>57248d11-5c60-484d-aa20-716dd04ef0aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
