<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextaddress_button</name>
   <tag></tag>
   <elementGuidId>116b214e-10af-4983-bebc-8036c75e2ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address > div.container > div.next-tab-area > #next-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='next-tab'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[4]/a[count(. | //a[@class = 'my-btn btn-red' and @id = 'next-tab' and (text() = 'NEXT' or . = 'NEXT')]) = count(//a[@class = 'my-btn btn-red' and @id = 'next-tab' and (text() = 'NEXT' or . = 'NEXT')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a8b5ee4-732a-481b-b8b6-695df4455b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-btn btn-red</value>
      <webElementGuid>879ecd0d-1b63-4a33-8553-07b7bb733fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next-tab</value>
      <webElementGuid>f5c1a568-8969-45ae-929e-712067326905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>ad24a115-113a-45ae-bf19-7f25d7410ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Validate('#address-tab', 2, true)</value>
      <webElementGuid>356bb557-0c80-4047-9dfa-08c1282c7f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>c4ccad89-e6ff-471d-a95c-5a436bb7d0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[4]/a</value>
      <webElementGuid>509a9a77-1862-43d7-8964-af7031f84a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='next-tab'])[2]</value>
      <webElementGuid>7694e42f-0da4-447d-8d68-b731b7cadc51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address']/div/div[4]/a</value>
      <webElementGuid>a353b355-e20b-4642-94c6-4fd1f312dd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'NEXT')])[2]</value>
      <webElementGuid>5dd80b33-30f3-42f7-9e8a-4e1e8dc645ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVED ADDRESSES'])[1]/following::a[1]</value>
      <webElementGuid>2fc0b9b9-a6de-4519-94a9-90c714104cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POSTAL CODE'])[1]/following::a[1]</value>
      <webElementGuid>615ba9db-3d30-449f-8fd6-7ae36a32ee7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/preceding::a[1]</value>
      <webElementGuid>440db507-7738-485f-a515-a78ed30b7949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash on delivery'])[1]/preceding::a[1]</value>
      <webElementGuid>614c5be6-2ab0-4be2-8f6e-6ab95c668c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>70b57f4a-ff6f-47f9-834c-9241b81c99b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>497cc3ba-d5bb-49c4-b965-ee64be5dae0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'next-tab' and @href = 'javascript:void(0);' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>19ebfebe-1501-48f1-96c7-7c41970e3589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
