<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextprofile_button</name>
   <tag></tag>
   <elementGuidId>c8dfe9ef-3154-43f6-bc38-b2c0ef92dc80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='next-tab']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[3]/a[count(. | //a[@class = 'my-btn btn-red' and @id = 'next-tab' and (text() = 'NEXT' or . = 'NEXT')]) = count(//a[@class = 'my-btn btn-red' and @id = 'next-tab' and (text() = 'NEXT' or . = 'NEXT')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5433d06-6b56-4477-9be6-803bbecda0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-btn btn-red</value>
      <webElementGuid>1f0ed329-ac8f-4909-beda-329d924d7ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Validate('#address-tab', 1, true, null, null, true)</value>
      <webElementGuid>1f577dcb-7421-4489-ba52-a1bd2ac32e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next-tab</value>
      <webElementGuid>ebff97ec-aa72-4de4-a2da-fc2145379561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>6195fe9d-c52e-41dd-8755-fdf74b66900a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>21d70b84-2613-4eeb-9f7e-434700bc4d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[3]/a</value>
      <webElementGuid>c52169b2-89b8-4e07-bc0b-f4ddde3e0b33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='next-tab']</value>
      <webElementGuid>9bb409a3-7514-4213-9a90-9fdf8fe05200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div[3]/a</value>
      <webElementGuid>ff5025f7-7bc4-4b68-8dae-273f6fce2e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NEXT')]</value>
      <webElementGuid>d45ebf4b-1313-4744-bf5c-3cd4b3c31055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seller Location'])[1]/following::a[1]</value>
      <webElementGuid>e3923961-008b-4c36-b8cb-3eecb757f6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPENID LOGIN'])[1]/following::a[1]</value>
      <webElementGuid>18dfabb4-fd89-440c-b593-f4ada2eb90cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW DELIVERY ADDRESS'])[1]/preceding::a[1]</value>
      <webElementGuid>dd7564f2-6a0e-48b2-af7d-b9b9acde19a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESSEE FIRST NAME'])[1]/preceding::a[1]</value>
      <webElementGuid>72be8b6f-da2c-49b2-84ab-8526c2cffd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT']/parent::*</value>
      <webElementGuid>dbcd3298-6bce-4cd7-ab08-c84250bf7919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[3]</value>
      <webElementGuid>afb21dfb-c0fc-48fb-8195-04faf523a3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/a</value>
      <webElementGuid>03a0cf6a-ed62-42bd-8b92-d69111713eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'next-tab' and @href = 'javascript:void(0);' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>8439aba1-bacd-4f96-a25f-c232aec36861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
