<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notification_email_textlabel</name>
   <tag></tag>
   <elementGuidId>e00a3392-bef2-4b90-beac-81ebf51a4775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/label[count(. | //label[(text() = 'NOTIFICATION EMAIL' or . = 'NOTIFICATION EMAIL')]) = count(//label[(text() = 'NOTIFICATION EMAIL' or . = 'NOTIFICATION EMAIL')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4d76fd12-bfd5-4f87-b10d-2d21da2f1983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NOTIFICATION EMAIL</value>
      <webElementGuid>6ab09d46-9827-47e3-bcfd-305d0cb11112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/label</value>
      <webElementGuid>b3032e8d-6015-4bc7-a997-75c941dc6988</webElementGuid>
   </webElementProperties>
</WebElementEntity>
