<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notification_email_textlabel</name>
   <tag></tag>
   <elementGuidId>e00a3392-bef2-4b90-beac-81ebf51a4775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/label[count(. | //label[(text() = 'NOTIFICATION EMAIL' or . = 'NOTIFICATION EMAIL')]) = count(//label[(text() = 'NOTIFICATION EMAIL' or . = 'NOTIFICATION EMAIL')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b79bb1f2-670c-4c6c-bcf6-377f7d69d444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NOTIFICATION EMAIL</value>
      <webElementGuid>46357c0b-ea47-4721-8a71-af1d2cc8b6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[1]/div/div[1]/form/div[5]/div[1]/label</value>
      <webElementGuid>70ed90f4-9be0-428b-a315-d71f65440ad4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
