<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_description_textlabel</name>
   <tag></tag>
   <elementGuidId>5feac03b-e346-4363-95a1-ae4c459d0ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[1]/div/div/p[count(. | //p[(text() = 'Configure your profile, your delivery methods and how you receive payments.' or . = 'Configure your profile, your delivery methods and how you receive payments.')]) = count(//p[(text() = 'Configure your profile, your delivery methods and how you receive payments.' or . = 'Configure your profile, your delivery methods and how you receive payments.')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c9499951-9ec1-4430-bd2f-c236015a0ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configure your profile, your delivery methods and how you receive payments.</value>
      <webElementGuid>53dfb7ff-aa38-4da7-88f4-2361a84d03b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[1]/div/div/p</value>
      <webElementGuid>155dbf06-a9f5-428e-9712-91363fe05a6f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
