<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payment_method_textlabel</name>
   <tag></tag>
   <elementGuidId>2d3b8dc6-cfa8-48d3-a27a-addbd144176d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment_acceptance']/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[1]/p[1][count(. | //p[(text() = 'Payment Method' or . = 'Payment Method')]) = count(//p[(text() = 'Payment Method' or . = 'Payment Method')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.seller-setting-p > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1b78101f-88c5-46a8-aaf2-7a942caebee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Method</value>
      <webElementGuid>366c6214-e637-4168-9991-f4c60df909d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[1]/p[1]</value>
      <webElementGuid>1ca08a03-cdf5-4043-a5f9-b66b77032109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment_acceptance']/div/div/div/div/p</value>
      <webElementGuid>ba96a586-c95c-4361-b1cd-5760d49c1a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[2]/following::p[1]</value>
      <webElementGuid>e3cdb4af-ab0b-4754-aa25-21a18180e6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test testtestAlbaniatesttesttest'])[1]/following::p[1]</value>
      <webElementGuid>38a92a82-547f-4c18-bc44-b7ce77f366bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash on delivery'])[1]/preceding::p[2]</value>
      <webElementGuid>b1c124ad-93bf-4b23-9dfa-9b98c0c9af03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/p</value>
      <webElementGuid>fb2362f7-988c-41a9-bf29-730d23a51113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Payment Method' or . = 'Payment Method')]</value>
      <webElementGuid>1b6a3515-52a2-4add-8e24-32616f24949e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
