<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payment_method_textlabel</name>
   <tag></tag>
   <elementGuidId>2d3b8dc6-cfa8-48d3-a27a-addbd144176d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[1]/p[1][count(. | //p[(text() = 'Payment Method' or . = 'Payment Method')]) = count(//p[(text() = 'Payment Method' or . = 'Payment Method')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment_acceptance']/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.seller-setting-p > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d4fc5675-7dc9-429f-89a6-1d911d6096f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Method</value>
      <webElementGuid>5476596f-a9fc-4cb8-beef-5a122d75506e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[1]/p[1]</value>
      <webElementGuid>c02d81bb-6821-455b-8e2b-1c517412c73e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment_acceptance']/div/div/div/div/p</value>
      <webElementGuid>022a41ee-ffb9-4b9e-bf78-06c3f7ec70ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[2]/following::p[1]</value>
      <webElementGuid>6339bf14-d749-4475-8226-f82ab1888d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test testtestAlbaniatesttesttest'])[1]/following::p[1]</value>
      <webElementGuid>c6e4785c-0913-439c-8a37-42ff411426db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash on delivery'])[1]/preceding::p[2]</value>
      <webElementGuid>379553ba-7636-46aa-baf2-f3d3c9a538f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/p</value>
      <webElementGuid>969c237b-64bf-4c97-8d33-5ccdb151bd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Payment Method' or . = 'Payment Method')]</value>
      <webElementGuid>cfb815db-f3ce-4601-a688-2733ee86713e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
