<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>postalcode_textlabel</name>
   <tag></tag>
   <elementGuidId>38b79e90-a806-4ab9-8d86-9f7d67c851ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[3]/div[4]/label[count(. | //label[(text() = 'POSTAL CODE' or . = 'POSTAL CODE')]) = count(//label[(text() = 'POSTAL CODE' or . = 'POSTAL CODE')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address-fields']/div[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ea4dbf73-c3f2-43f8-b6a8-8352f2cdc0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>POSTAL CODE</value>
      <webElementGuid>fffa7537-aad7-4a1c-854f-f0fb94cc3cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[3]/div[4]/label</value>
      <webElementGuid>7f2b758d-4b30-4f84-974c-11db36fa4b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-fields']/div[4]/label</value>
      <webElementGuid>0fa7f949-efcd-481f-a1d1-75920509791c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CITY'])[1]/following::label[1]</value>
      <webElementGuid>6d9b94e2-18bf-4b97-a0cf-a93f20ea207f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STATE'])[1]/following::label[2]</value>
      <webElementGuid>64aad179-565e-4828-a795-3731cd8e159d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVED ADDRESSES'])[1]/preceding::label[1]</value>
      <webElementGuid>a583673b-d095-491f-8134-3a706a08a62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[2]/preceding::label[1]</value>
      <webElementGuid>5fdf2df2-4ed8-4a0c-9c22-80f4e1e4db36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='POSTAL CODE']/parent::*</value>
      <webElementGuid>45cde231-661d-4711-9dea-753ae49d1883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>889dc547-8755-40c3-b6a8-66481077b465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'POSTAL CODE' or . = 'POSTAL CODE')]</value>
      <webElementGuid>2ec60331-4a10-4fa6-a6bf-8ab7c21aa19f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
