<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_tab</name>
   <tag></tag>
   <elementGuidId>bd613c21-a8a4-4fd1-9f5a-dae19d2c774a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/ul/li[1]/a[count(. | //a[@id = 'profile-tab']) = count(//a[@id = 'profile-tab'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profile-tab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>147f204f-c511-402a-907b-ec631a857a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile-tab</value>
      <webElementGuid>dcdc3442-95f7-49a0-8268-6e4c5041332a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/ul/li[1]/a</value>
      <webElementGuid>37951afb-0c90-4904-a4a4-83ecc0c294d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile-tab']</value>
      <webElementGuid>f068b35c-425c-4a13-999a-9fdc075b7fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='setting-tab']/li/a</value>
      <webElementGuid>1f9c0ca7-47f6-4946-a0c1-9259951b8048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER SETTINGS'])[1]/following::a[1]</value>
      <webElementGuid>9bab8f76-2a62-4f7b-8306-bd2c2cc9041e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[2]/following::a[2]</value>
      <webElementGuid>3addff8d-6aa6-443c-9be8-76bf3453e99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESS'])[1]/preceding::a[1]</value>
      <webElementGuid>868f2ce8-3ce1-4d7c-8ec3-9e87e6ca3de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#profile')]</value>
      <webElementGuid>27df0fb8-eb35-4fd6-a36a-33b5d37f5b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/ul/li/a</value>
      <webElementGuid>7820bd51-9ff6-45f3-a527-5842b3ed8785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#profile' and @id = 'profile-tab' and (text() = '
                PROFILE
            ' or . = '
                PROFILE
            ')]</value>
      <webElementGuid>a917f0d2-74e9-496a-b628-85ee5d4f1c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
