<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_tab</name>
   <tag></tag>
   <elementGuidId>bd613c21-a8a4-4fd1-9f5a-dae19d2c774a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profile-tab']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae162f56-09b6-4368-aaee-a61126313f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile-tab</value>
      <webElementGuid>1192c203-6404-4e25-851c-81c965919335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/ul/li[1]/a</value>
      <webElementGuid>aa16d0e0-3887-4cfb-8c69-6f5a92a6780c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile-tab']</value>
      <webElementGuid>b0ead7a1-acb2-4306-848b-6604f7dac8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='setting-tab']/li/a</value>
      <webElementGuid>fab9c4b5-4a3e-4999-aec9-584955ae67e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER SETTINGS'])[1]/following::a[1]</value>
      <webElementGuid>20d98d64-d377-4af1-aed0-00ee9b2e1c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[2]/following::a[2]</value>
      <webElementGuid>90653be7-4bac-4bd6-8c6b-21f082564e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESS'])[1]/preceding::a[1]</value>
      <webElementGuid>c0895d3f-2845-4b7d-a78a-1b7559f082a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#profile')]</value>
      <webElementGuid>9bf163a2-20d9-4dd2-80d6-fa3e4bf8ee67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/ul/li/a</value>
      <webElementGuid>a20ab352-f465-4a60-87ac-a4789bd9b6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#profile' and @id = 'profile-tab' and (text() = '
                PROFILE
            ' or . = '
                PROFILE
            ')]</value>
      <webElementGuid>eb81b76d-5133-4ac5-ab46-5b68470ad37a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
