<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_tab</name>
   <tag></tag>
   <elementGuidId>bd613c21-a8a4-4fd1-9f5a-dae19d2c774a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='profile-tab']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>34aa1c93-2c9f-4eef-8a8d-47ed6aba5e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile-tab</value>
      <webElementGuid>28d67436-51b0-4227-9fdd-609f5525e3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/ul/li[1]/a</value>
      <webElementGuid>2dbfa085-a597-481b-a769-f5d65c52611c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='profile-tab']</value>
      <webElementGuid>ee50c914-976e-4529-8953-039c1cc8cc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='setting-tab']/li/a</value>
      <webElementGuid>f20b2d7a-b7c2-4090-98b4-04e79ce0fd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER SETTINGS'])[1]/following::a[1]</value>
      <webElementGuid>7a907f3b-6edf-49d8-951f-2d7159af557d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[2]/following::a[2]</value>
      <webElementGuid>591cc8b4-c968-400e-9e61-bd515b814b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESS'])[1]/preceding::a[1]</value>
      <webElementGuid>0ad79057-db3f-4210-b1e7-d799f0d0eadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#profile')]</value>
      <webElementGuid>9879ffeb-0dcc-4f3f-ad42-6852d9fda1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/ul/li/a</value>
      <webElementGuid>b5a8ae3b-7925-4f27-9bdd-8ce07fc1d8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#profile' and @id = 'profile-tab' and (text() = '
                PROFILE
            ' or . = '
                PROFILE
            ')]</value>
      <webElementGuid>7a02c0e2-7c31-47f8-8aaa-0587c97bcdfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
