<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saved_address_textlabel</name>
   <tag></tag>
   <elementGuidId>4ac439d0-a53f-4bae-aeb8-63be182338e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div[1]/h4[count(. | //h4[@class = 'title' and (text() = 'SAVED ADDRESSES' or . = 'SAVED ADDRESSES')]) = count(//h4[@class = 'title' and (text() = 'SAVED ADDRESSES' or . = 'SAVED ADDRESSES')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address']/div/div[2]/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>4806c496-cf8b-4b9a-85e2-7a45f1db12cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>cf35f257-136e-489b-8122-3d5064211352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAVED ADDRESSES</value>
      <webElementGuid>0c0d8477-48ce-4543-9d6f-b0c5d903636f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div[1]/h4</value>
      <webElementGuid>f7caa78b-1537-44d9-b0e6-1d3745259198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address']/div/div[2]/div/h4</value>
      <webElementGuid>79178dee-9c2c-46b6-94cf-59c9adf862b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POSTAL CODE'])[1]/following::h4[1]</value>
      <webElementGuid>f1071484-e1bb-4e34-8032-94aac0569f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CITY'])[1]/following::h4[1]</value>
      <webElementGuid>e2f601e7-bff2-48e6-8cc9-77110c889248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[2]/preceding::h4[1]</value>
      <webElementGuid>5efe49e0-5d3b-4499-a46c-525a3997ee34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/preceding::h4[1]</value>
      <webElementGuid>1f54498b-730d-494d-a0b0-dff4890d41d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SAVED ADDRESSES']/parent::*</value>
      <webElementGuid>a1bbf802-7f47-433f-bfa8-708bd61d2b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h4</value>
      <webElementGuid>e69d579f-fed8-4390-a9ca-9ed4e782bb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'SAVED ADDRESSES' or . = 'SAVED ADDRESSES')]</value>
      <webElementGuid>258ba442-d29c-477c-9bd7-f097a4c2df87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
