<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saved_address_textlabel</name>
   <tag></tag>
   <elementGuidId>4ac439d0-a53f-4bae-aeb8-63be182338e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address']/div/div[2]/div/h4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div[1]/h4[count(. | //h4[@class = 'title' and (text() = 'SAVED ADDRESSES' or . = 'SAVED ADDRESSES')]) = count(//h4[@class = 'title' and (text() = 'SAVED ADDRESSES' or . = 'SAVED ADDRESSES')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>6609f1dc-25a9-47ef-ad2c-dcac8b899f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>03d46a32-d13a-4590-87d2-e526afa5ae8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAVED ADDRESSES</value>
      <webElementGuid>04d2ffed-ad84-4398-af3a-559f1666a779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div[1]/h4</value>
      <webElementGuid>06b53318-e58e-4912-b3c4-d5f1bfd5c989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address']/div/div[2]/div/h4</value>
      <webElementGuid>cc58e3fd-0e81-4905-8250-87bda8c6cbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POSTAL CODE'])[1]/following::h4[1]</value>
      <webElementGuid>6fdc977f-1d17-4c07-92e0-4ec876b90b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CITY'])[1]/following::h4[1]</value>
      <webElementGuid>31bfc2ad-310a-4b70-9561-e63a0af9e50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[2]/preceding::h4[1]</value>
      <webElementGuid>f4d38ed2-3881-4358-a723-85ff359772a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/preceding::h4[1]</value>
      <webElementGuid>da29e503-97c1-4d12-9ef5-37d3faac9182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SAVED ADDRESSES']/parent::*</value>
      <webElementGuid>35b884c9-488d-43f5-9c50-60eb93bd0677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h4</value>
      <webElementGuid>274f9d90-dfe9-4e79-9fd6-8331ae736e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'SAVED ADDRESSES' or . = 'SAVED ADDRESSES')]</value>
      <webElementGuid>cdf635db-aa6b-4664-acf6-c95875fd3cab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
