<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save_image_btn</name>
   <tag></tag>
   <elementGuidId>f6a3fc19-50fe-430c-baa1-46676b28d058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[6]/div/div/div/div/div[4]/a[count(. | //a[@class = 'btn btn-warning download']) = count(//a[@class = 'btn btn-warning download'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41d02834-fc2b-4248-bdca-af3a8ec968af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning download</value>
      <webElementGuid>ec15af60-1155-4997-9311-66428b27b3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[6]/div/div/div/div/div[4]/a</value>
      <webElementGuid>b4c2369f-fd1c-45a6-b29b-ca87c08bbfc9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
