<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save_button</name>
   <tag></tag>
   <elementGuidId>fa1efeb5-c4bb-498e-b8f9-93bde786cefd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_acceptance > div.container > div.next-tab-area > #next-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='next-tab'])[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'my-btn btn-red' and @id = 'next-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e10ae948-0223-45e5-afd5-761852c0ac4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-btn btn-red</value>
      <webElementGuid>3fef9d44-179d-40c6-87ea-c90c7ba0964d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Validate('undefined', 3, true)</value>
      <webElementGuid>b8af9bbd-472e-4b17-83c7-8afdffe3980a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next-tab</value>
      <webElementGuid>c3281bb5-27a2-4496-8b39-47979d3e6912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>50611ca2-bf8d-4ac6-990d-0071156a5551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&#xd;
                                SAVE&#xd;
                            </value>
      <webElementGuid>0085afec-3f11-486f-bb46-9eacd7e8926c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[3]/div/div[5]/a</value>
      <webElementGuid>05b2bb6d-8364-4833-8574-634f7ef23f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='next-tab'])[5]</value>
      <webElementGuid>8e00171a-0e11-4cd9-b3ef-665119be8982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment_acceptance']/div/div[5]/a</value>
      <webElementGuid>d28d9408-7de5-4811-ac53-f522c0f02f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SAVE')]</value>
      <webElementGuid>703bfec2-874d-4833-899b-f491fa53d111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::a[1]</value>
      <webElementGuid>382c4c07-6ad7-4ebf-af9a-aa8b2eb0c882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account Name'])[1]/following::a[2]</value>
      <webElementGuid>9243ae67-e78b-4b65-81bb-aead76f0b6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABOUT US'])[1]/preceding::a[1]</value>
      <webElementGuid>956b9928-e865-443d-aa24-e57a7ba51bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TERMS OF SERVICE'])[1]/preceding::a[2]</value>
      <webElementGuid>369f2f0f-b7ee-4e15-b63e-25a735d2be96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SAVE']/parent::*</value>
      <webElementGuid>0a4c9846-37ea-4653-a89f-d307ad697fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[10]</value>
      <webElementGuid>2bd9cde7-e130-41cd-83d1-7424e601a647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>1d30a5f4-90aa-43c0-b4a1-84a423002ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'next-tab' and @href = 'javascript:void(0);' and (text() = '
                                SAVE
                            ' or . = '
                                SAVE
                            ')]</value>
      <webElementGuid>c9c6f21f-4a0e-4bfc-a570-fea738f98cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
