<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>seller_location_textbox</name>
   <tag></tag>
   <elementGuidId>7f641601-b43e-44a1-a813-267db936a1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;input-seller-location&quot;)[count(. | //input[@type = 'text' and @name = 'SellerLocation' and @id = 'input-seller-location']) = count(//input[@type = 'text' and @name = 'SellerLocation' and @id = 'input-seller-location'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-seller-location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-seller-location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d54348e-e691-4a7b-85d4-4ce785f69bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69e13e9a-e6b2-4c5d-9855-73955ca08186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SellerLocation</value>
      <webElementGuid>b84fc202-44e5-4ce3-ba32-dc9be3288c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-seller-location</value>
      <webElementGuid>debd0ed1-8d6f-4a2a-b30c-fb683fd64fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-seller-location&quot;)</value>
      <webElementGuid>8058519c-a7c8-4d71-88f5-52421034e498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-seller-location']</value>
      <webElementGuid>f1e03612-bdda-4f6d-9120-b1270afdcd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile']/div/div/form/div[6]/div[2]/input</value>
      <webElementGuid>9afcff8d-77ee-488e-8a0c-bcae1516e06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>aaa82d26-6554-4259-9c0e-cf32209fa1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SellerLocation' and @id = 'input-seller-location']</value>
      <webElementGuid>4d31b454-fd91-4919-8a56-caf09969f669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
