<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>state_textlabel</name>
   <tag></tag>
   <elementGuidId>9e2d632d-d629-4b3e-92e9-4a2aaae9d866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[3]/div[2]/label[count(. | //label[(text() = 'STATE' or . = 'STATE')]) = count(//label[(text() = 'STATE' or . = 'STATE')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address-fields']/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3fab6637-72c0-4553-91e4-4c84b4952b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STATE</value>
      <webElementGuid>76e16fdc-3bf7-4780-8d22-0510d4de42e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[2]/div/div[1]/form/div[3]/div[2]/label</value>
      <webElementGuid>64f79d6c-6a45-4c7e-aa84-b470c81d75ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-fields']/div[2]/label</value>
      <webElementGuid>3e4dab53-f114-4f99-832e-bb8d6de66e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COUNTRY'])[1]/following::label[1]</value>
      <webElementGuid>de45a04b-3708-4860-a73d-d0225cd25f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDRESS'])[2]/following::label[2]</value>
      <webElementGuid>b6af41ea-a600-47b7-92a9-a1ab3298ecc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CITY'])[1]/preceding::label[1]</value>
      <webElementGuid>6bdc9941-f614-4c85-83bd-47c02869bde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POSTAL CODE'])[1]/preceding::label[2]</value>
      <webElementGuid>9c1a34e3-fc67-4b49-a0a1-84464525d69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='STATE']/parent::*</value>
      <webElementGuid>0d0a62ed-b59b-4f29-9271-adb815e0de49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/label</value>
      <webElementGuid>998b3c7a-0b73-4a6f-8502-fc17daebed27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'STATE' or . = 'STATE')]</value>
      <webElementGuid>e01d8bf7-e47e-4cbd-920a-1779eb21c3fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
