<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verified_icon</name>
   <tag></tag>
   <elementGuidId>b4903436-d853-4c7c-9e9e-6e7237b0a41b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[4]/div[count(. | //div[@class = 'verified-icon']) = count(//div[@class = 'verified-icon'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5240919b-1568-41f8-a3ec-0f3f03b42b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verified-icon</value>
      <webElementGuid>ddda8d5a-185f-40a5-b884-8d3e71d10b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[4]/div</value>
      <webElementGuid>623fe6cc-15fa-432d-a4ce-a362319b1bb3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
