<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verified_text</name>
   <tag></tag>
   <elementGuidId>c1bb686e-a3e5-4954-a5e4-1abbf3f551c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[4]/span[count(. | //span[@class = 'verified-text' and (text() = 'Verified' or . = 'Verified')]) = count(//span[@class = 'verified-text' and (text() = 'Verified' or . = 'Verified')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>209a7195-3106-4c08-8edd-41a2142b5baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verified-text</value>
      <webElementGuid>027b3d24-9665-4ef9-9b9c-3afe8b98408b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verified</value>
      <webElementGuid>013a3bca-8ab7-4375-a34d-9e408ce886e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[4]/span</value>
      <webElementGuid>ae2342b2-42e6-4e5d-bdec-b50cc6c209a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
