<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>warning_icon</name>
   <tag></tag>
   <elementGuidId>44855ff8-fa10-4133-8451-05f27d03fc5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment_acceptance']/div/div/div/div[2]/div[4]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[4]/div[count(. | //div[@class = 'img-payment-warning']) = count(//div[@class = 'img-payment-warning'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.img-payment-warning</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfe8ce61-80e2-45d4-bae7-d160da88226a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-payment-warning</value>
      <webElementGuid>c5d50f42-4b4d-402e-b189-254474ee97b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div[2]/div/div[3]/div/div[1]/div/div[2]/div[4]/div</value>
      <webElementGuid>e7a5c4f8-14d2-47e8-ac6d-0eeda0069950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment_acceptance']/div/div/div/div[2]/div[4]/div</value>
      <webElementGuid>9e3454dc-b44b-45ad-8898-508a977c4550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>e5a4a778-a21c-423b-8c07-e12727415f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
