<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zoom_reset_btn</name>
   <tag></tag>
   <elementGuidId>e998b456-ea01-43c3-9f90-d116ba5a2fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[6]/div/div/div/div/div[2]/div[2][count(. | //div[@class = 'btn btn-default btn-zoom-reset' and @title = 'Fullsize']) = count(//div[@class = 'btn btn-default btn-zoom-reset' and @title = 'Fullsize'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e40f7cdb-9885-402f-9f63-a13270f453a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-zoom-reset</value>
      <webElementGuid>4193fa94-eec1-47e9-8fe6-6dfd387f430c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Fullsize</value>
      <webElementGuid>1017c628-83f6-4a48-b13d-7571e4b43e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[6]/div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>eb42e521-cd23-4c79-8ed8-54ddb7366d40</webElementGuid>
   </webElementProperties>
</WebElementEntity>
