<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Oops Something went wrong.That user name is taken. Please try again with a different user name</name>
   <tag></tag>
   <elementGuidId>0412d3bc-0cf2-40f4-83f0-b7cc964307b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.toast.toast-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b12c53f-d3d4-4973-af02-30f28a8a4759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast toast-error</value>
      <webElementGuid>61c1b3f4-6ecb-483f-bf30-883e941eefab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oops! Something went wrong.That user name is taken. Please try again with a different user name.</value>
      <webElementGuid>74665f69-ced2-44f7-b30e-89bde2e9348b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;toast toast-error&quot;]</value>
      <webElementGuid>e1dfd4cb-fe71-458d-b0d2-442475e362ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>faca0fc7-3f5c-4054-a619-1bdd3b95850d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bespokeautomationken'])[2]/following::div[18]</value>
      <webElementGuid>b45b63a0-6901-4f3a-a8e2-aa07bf1d84fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT US'])[1]/following::div[20]</value>
      <webElementGuid>0927e8f8-26d4-4850-b99f-b68c21f71f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div</value>
      <webElementGuid>5eb6745c-4669-4b91-9fa2-0a8e2d1f882d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Oops! Something went wrong.That user name is taken. Please try again with a different user name.' or . = 'Oops! Something went wrong.That user name is taken. Please try again with a different user name.')]</value>
      <webElementGuid>1d06ce05-24ec-4b78-af07-647768901797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
